import processing.svg.*;
import processing.serial.*;


// ---------- MODE SELECTION ----------
boolean STANDALONE_MODE = true;
String SERIAL_PORT_NAME = "";       // auto-detect first port if blank

// ---------- SERIAL ----------
Serial arduinoPort = null;
float arduinoFx = 0, arduinoFy = 0;

// ---------- VELOCITY TRACKING ----------
float xh_prev = 0, yh_prev = 0;
float vx_filt = 0, vy_filt = 0;
float DT_LOOP = 0.001f;


// ---------- RENDERING CONDITION ----------
boolean texturedMode = true;

// ---------- PHYSICAL <-> SCREEN MAPPING ----------
float PIXELS_PER_METER = 4000.0f;
float ORIGIN_X, ORIGIN_Y;

// ---------- FORCE MODEL PARAMETERS (must match .ino) ----------
float K_WALL       = 2000.0f;
float B_WALL       = 15.0f;
float P_T          = -0.003f;
float A_GUIDE      = 0.5f;
float C_GUIDE      = 200.0f;
float F_GUIDE_MAX  = 2.0f;
float A_TEX        = 0.30f;
float LAMBDA_TEX   = 0.0020f;

// ---------- SHAPE DATA (must match .ino) ----------
// Three shapes, each 200 points, CCW, normalized to fit ~7 cm bounding box.
// Auto-generated by preprocess_shapes.py from the team's SVG-derived CSVs.
// Data is retrieved from saved csv files.

ShapeRecord currentShape;
int shape_id = 3; // 1, 2 and 3
PShape baseSVG;
float[][] points;

// Precomputed arc-length table (sized for max possible):
float[] s_arc;
float perimeter;
float lambda_actual;

// --- Settings ---
color dotColor = color(226, 75, 74);
color lineColor = color(55, 138, 221);
float dotRadius = 5;
float lineWeight = 2;
float dotOpacity = 230;
float lineOpacity = 180;
float padding = 150;  // pixels of whitespace on each side

// --- display options ---
boolean showLines = true;
boolean showDots = true;
boolean showLabels = false;


void setup() {
  // set up screen
  size(900, 900);
  ORIGIN_X = width / 2.0f;
  ORIGIN_Y = height / 2.0f;
  
  setupSerial();
  
  // connect to database
  dbConnect();
  
  // set shape
  setShape(shape_id);
  
}

void draw() {
  background(255);

  // update user position // TODO: update with values from serial
  float xh = (mouseX - ORIGIN_X) / PIXELS_PER_METER;
  float yh = -(mouseY - ORIGIN_Y) / PIXELS_PER_METER;

  // draw user
  drawPenTip(xh, yh);

  // draw shape
  drawLines();
  drawDots();

}

// run this on exit of the processing app, so we protect the database
void exit() {
  dbClose();
  super.exit();
}


float[][] loadCoordinates(String filename) {
  String[] lines = loadStrings(filename);
  if (lines == null) {
    println("Could not load " + filename);
    return new float[0][2];
  }
  
  int count = 0;
  for (String line : lines) {
    line = line.trim();
    if (line.isEmpty()) continue;
    String[] parts = splitTokens(line, ",;\t");
    if (parts.length >= 2) {
      try {
        Float.parseFloat(parts[0].trim());
        Float.parseFloat(parts[1].trim());
        count++;
      } catch (NumberFormatException e) {}
    }
  }
  
  float[][] pts = new float[count][2];
  int idx = 0;
  for (String line : lines) {
    line = line.trim();
    if (line.isEmpty()) continue;
    String[] parts = splitTokens(line, ",;\t");
    if (parts.length >= 2) {
      try {
        float rawX = Float.parseFloat(parts[0].trim());
        float rawY = Float.parseFloat(parts[1].trim());
        pts[idx][0] = meterToPixelX(rawX);
        pts[idx][1] = meterToPixelY(rawY);
        idx++;
      } catch (NumberFormatException e) {}
    }
  }
  
  return pts;
}


void setShape(int id) {
  // get shape info from db
  currentShape = getCurrentShape(id);
  
  // load + read svg
  baseSVG = loadShape(currentShape.svgFilename);
  
  // load csv coordinates
  points = loadCoordinates(currentShape.csvFilename);
  println("Loaded " + points.length + " points");
  
  precomputeArcLength();
  println("Active shape: " + currentShape.shapeName + " (" + points.length + " pts)");

  // Tell Arduino too, if connected.
  if (arduinoPort != null) {
    if (shape_id == 0)      arduinoPort.write('B');
    else if (shape_id == 1) arduinoPort.write('H');
    else if (shape_id == 2) arduinoPort.write('P');
  }
}

void precomputeArcLength() {
  s_arc = new float[points.length];
  s_arc[0] = 0;
  for (int i = 1; i < points.length; i++) {
    float dx = points[i][0] - points[i-1][0];
    float dy = points[i][1] - points[i-1][1];
    s_arc[i] = s_arc[i-1] + sqrt(dx*dx + dy*dy);
  }
  float dx_close = points[0][0] - points[points.length-1][0];
  float dy_close = points[0][1] - points[points.length-1][1];
  perimeter = s_arc[points.length-1] + sqrt(dx_close*dx_close + dy_close*dy_close);

  int n_cycles = round(perimeter / LAMBDA_TEX);
  if (n_cycles < 1) n_cycles = 1;
  lambda_actual = perimeter / n_cycles;
  println("Perimeter: " + perimeter + " m, " + n_cycles + " texture cycles, " +
          "lambda = " + lambda_actual + " m");
}


// =============================================================
// SERIAL
// =============================================================
void setupSerial() {
  if (STANDALONE_MODE) return;
  String[] ports = Serial.list();
  println("Available serial ports:");
  for (int i = 0; i < ports.length; i++) {
    println("  [" + i + "] " + ports[i]);
  }
  if (ports.length == 0) {
    println("No serial ports found; staying in STANDALONE mode.");
    STANDALONE_MODE = true;
    return;
  }
  String portName = SERIAL_PORT_NAME.isEmpty() ? ports[0] : SERIAL_PORT_NAME;
  println("Connecting to: " + portName);
  arduinoPort = new Serial(this, portName, 115200);
  arduinoPort.bufferUntil('\n');
}

// =============================================================
// VISUAL RENDERING
// =============================================================
float meterToPixelX(float xm) { return ORIGIN_X + xm * PIXELS_PER_METER; }
float meterToPixelY(float ym) { return ORIGIN_Y - ym * PIXELS_PER_METER; }


void drawPenTip(float xh, float yh) {
  noStroke();
  fill(255, 100, 150);
  ellipse(meterToPixelX(xh), meterToPixelY(yh), 12, 12);
}

void drawDots() {
  fill(red(dotColor), green(dotColor), blue(dotColor), dotOpacity);
    noStroke();
    for (int i = 0; i < points.length; i++) {
      ellipse(points[i][0], points[i][1], dotRadius * 2, dotRadius * 2);
    }
}

void drawLines() {
    strokeWeight(lineWeight);
    stroke(red(lineColor), green(lineColor), blue(lineColor), lineOpacity);
    noFill();
    for (int i = 0; i < points.length - 1; i++) {
      line(points[i][0], points[i][1], points[i+1][0], points[i+1][1]);
    }
}
