import processing.svg.*;
import processing.serial.*;


// ---------- MODE SELECTION ----------
boolean STANDALONE_MODE = false;
Serial[] arduinoPorts = new Serial[0];
boolean TEST = false; // 0=off, 1=on — draws a test square + pen tip only

// ---------- SERIAL ----------
Serial arduinoPort = null;
float arduinoFx = 0, arduinoFy = 0;   // pen tip position from Arduino (named Fx/Fy historically; actually x/y)
float arduinoForceX = 0, arduinoForceY = 0;   // force from Arduino force model

// ---- Proxy stuff ----
int   proc_proxy_seg = 0;
float proc_proxy_t   = 0.0f;
boolean proc_was_inside = false;
float proc_proxy_px = 0, proc_proxy_py = 0;
float pen_px_prev = 0, pen_py_prev = 0;



// ---------- VELOCITY TRACKING ----------
float xh_prev = 0, yh_prev = 0;
float vx_filt = 0, vy_filt = 0;
float DT_LOOP = 0.001f;


// ---------- RENDERING CONDITION ----------
boolean texturedMode = true;

// ---------- PHYSICAL <-> SCREEN MAPPING ----------
float PIXELS_PER_METER = 4000.0f;
float ORIGIN_X, ORIGIN_Y;
float WORKSPACE_CENTER_X = 0.0;  // fill in from serial monitor
float WORKSPACE_CENTER_Y = 0.1; // fill in from serial monitor

// ---------- FORCE MODEL PARAMETERS (must match .ino) ----------
float K_WALL       = 200.0f;
float B_WALL       = 15.0f;
float P_T          = -0.003f;
float A_GUIDE      = 0.5f;
float C_GUIDE      = 200.0f;
float F_GUIDE_MAX  = 2.0f;
float A_TEX        = 0.30f;
float LAMBDA_TEX   = 0.0020f;

// ---------- SHAPE DATA (must match .ino) ----------
// Three shapes, each 200 points, CCW, normalized to fit ~7 cm bounding box.
// Auto-generated by preprocess_shapes.py from the team's SVG-derived CSVs.
// Data is retrieved from saved csv files.

ShapeRecord currentShape;
int shapeId= 5; // 1, 2 and 3
int lastShapeId = -1;
PShape baseSVG;
float[][] points;
String[] recentGuesses = new String[0];
int[] shapeQueue = new int[0];   // shuffled queue of upcoming shape ids
int queueIdx = 0;                // pointer into the queue

// Precomputed arc-length table (sized for max possible):
float[] s_arc;
float perimeter;
float lambda_actual;

// --- Settings ---
color dotColor = color(204, 171, 92);
color lineColor = color(248, 142, 181);
float dotRadius = 5;
float lineWeight = 2;
float dotOpacity = 230;
float lineOpacity = 180;
float padding = 150;  // pixels of whitespace on each side

// --- display options ---
int screen = 0; // 0 = guess input, 1 = results


// --- buttons + dropdowns ----
Button nextShapeBtn;
Dropdown shapeDropdown;
String[][] shapeNameList;
TextInput guessInput;
Button submitBtn;

void setup() {
  // set up screen
  size(900, 900);
  ORIGIN_X = width / 2.0f;
  ORIGIN_Y = height / 2.0f;
  
  setupSerial();
  dbConnect(); // needed to load the shape csv filename
  
  setShape(shapeId);
  nextShapeBtn   = new Button(700, 700, 120, 35, "Next");
  setupShapeDropdown();
  guessInput     = new TextInput(100, 200, 300, 40, "What do you think the shape is...");
  submitBtn      = new Button(500, 200, 120, 35, "Go");

  
}

void draw() {
  background(255);
  if (TEST) {
    drawTestMode();
    return;
  }
  
  if (screen == 0) drawGuessScreen();
  else drawResultsScreen();

  if (shapeId != lastShapeId) {
    lastShapeId = shapeId;
    setShape(shapeId);
    recentGuesses = loadRecentGuesses(shapeId);
    screen = 0; // when the shape changes, always go to guess screen
  }

}

void mousePressed() {
  nextShapeBtn.handleClick(mouseX, mouseY);
  shapeDropdown.handleClick(mouseX, mouseY);
  guessInput.handleClick(mouseX, mouseY);
  submitBtn.handleClick(mouseX, mouseY);
}

void keyPressed() {
  guessInput.handleKey();
}

// run this on exit of the processing app, so we protect the database
void exit() {
  dbClose();
  super.exit();
}

// ---- DRAW FUNCTIONS ----

void toggleScreen(){
 if (screen == 0) screen = 1;
 else screen = 0;
}

void drawTestMode() {
  if (shapeId != lastShapeId) {
    lastShapeId = shapeId;
    setShape(shapeId);
  }

  float xh = -(arduinoFx - WORKSPACE_CENTER_X);
  float yh = -(arduinoFy - WORKSPACE_CENTER_Y);

  drawLines();
  drawDots();
  drawPenAndProxy(xh, yh);  // replaces drawPenTip + drawForceVector
  shapeDropdown.draw();

  fill(80);
  textAlign(LEFT, TOP);
  textSize(12);
  text("TEST MODE — " + (currentShape != null ? currentShape.shapeName : ""), 10, 10);
  text("pen: (" + nf(arduinoFx, 1, 4) + ", " + nf(arduinoFy, 1, 4) + ") m", 10, 26);
}

void drawGuessScreen(){
  
  float xh = -(arduinoFx - WORKSPACE_CENTER_X);
  float yh = -(arduinoFy - WORKSPACE_CENTER_Y);
  drawPenAndProxy(xh, yh);  // blue dot shows here too
  
  guessInput.draw();
  submitBtn.draw();

  if (submitBtn.isClicked()) {
    String guess = guessInput.getValue();
    if (guess.length() > 0) {
      insertGuess(shapeId, guess);   // send guess to database
      recentGuesses = loadRecentGuesses(shapeId); // load once here
      guessInput.clear();
      screen = 1;         // move to results
    }
    submitBtn.reset();
  }
}

void drawResultsScreen(){
  // update user position
  float xh = -(arduinoFx - WORKSPACE_CENTER_X);
  float yh = -(arduinoFy - WORKSPACE_CENTER_Y);

  // draw user
  drawPenAndProxy(xh, yh);

  // draw shape
  drawLines();
  drawDots();
  
  // draw buttons
  nextShapeBtn.draw();
  shapeDropdown.draw();
  
  // draw recent guesses table
  drawGuessSidebar();
  
  if (nextShapeBtn.isClicked()){
    toggleShape();
    toggleScreen();
    nextShapeBtn.reset();
  }
}

// ----- OTHER FUNCTIONS -----

float[][] loadCoordinates(String filename) {
  String[] lines = loadStrings(filename);
  if (lines == null) {
    println("Could not load " + filename);
    return new float[0][2];
  }
  
  int count = 0;
  for (String line : lines) {
    line = line.trim();
    if (line.isEmpty()) continue;
    String[] parts = splitTokens(line, ",;\t");
    if (parts.length >= 2) {
      try {
        Float.parseFloat(parts[0].trim());
        Float.parseFloat(parts[1].trim());
        count++;
      } catch (NumberFormatException e) {}
    }
  }
  
  float[][] pts = new float[count][2];
  int idx = 0;
  for (String line : lines) {
    line = line.trim();
    if (line.isEmpty()) continue;
    String[] parts = splitTokens(line, ",;\t");
    if (parts.length >= 2) {
      try {
        float rawX = Float.parseFloat(parts[0].trim());
        float rawY = Float.parseFloat(parts[1].trim());
        pts[idx][0] = width - meterToPixelX(rawX);
        pts[idx][1] = height - meterToPixelY(rawY);
        idx++;
      } catch (NumberFormatException e) {}
    }
  }
  
  return pts;
}

void toggleShape(){
  // If the queue is empty or exhausted, reshuffle all 6 shapes
  if (shapeQueue.length == 0 || queueIdx >= shapeQueue.length) {
    shapeQueue = shuffleShapeIds();
    queueIdx = 0;
    // Avoid the first card matching the current shape (no immediate repeat
    // across a reshuffle). Swap it with another slot if it does.
    if (shapeQueue[0] == shapeId && shapeQueue.length > 1) {
      int tmp = shapeQueue[0];
      shapeQueue[0] = shapeQueue[1];
      shapeQueue[1] = tmp;
    }
  }
  shapeId = shapeQueue[queueIdx];
  queueIdx++;
}

// Fisher-Yates shuffle of shape ids 5..11
int[] shuffleShapeIds() {
  int[] arr = {5, 6, 7, 8, 9, 10, 11};
  for (int i = arr.length - 1; i > 0; i--) {
    int j = int(random(i + 1));
    int tmp = arr[i];
    arr[i] = arr[j];
    arr[j] = tmp;
  }
  return arr;
}


void setShape(int id) {
  // get shape info from db
  currentShape = getCurrentShape(id);
  
  // load csv coordinates
  points = loadCoordinates(currentShape.csvFilename);
  println("Loaded " + points.length + " points");
  
  precomputeArcLength();
  println("Active shape: " + currentShape.shapeName + " (" + points.length + " pts)");

  // Tell Arduino too, if connected.
  char cmd = 0;
  if      (shapeId == 5)  cmd = 'F';
  else if (shapeId == 6)  cmd = 'D';
  else if (shapeId == 7)  cmd = 'B';
  else if (shapeId == 8)  cmd = 'E'; // bell had to be 'E' bc we have banana as 'B'
  else if (shapeId == 9)  cmd = 'H'; // horseshoe
  else if (shapeId == 10) cmd = 'M'; // mushroom
  else if (shapeId == 11) cmd = 'S'; // square

  if (cmd != 0) {
    for (Serial p : arduinoPorts) p.write(cmd);
  }
}

void precomputeArcLength() {
  s_arc = new float[points.length];
  s_arc[0] = 0;
  for (int i = 1; i < points.length; i++) {
    float dx = points[i][0] - points[i-1][0];
    float dy = points[i][1] - points[i-1][1];
    s_arc[i] = s_arc[i-1] + sqrt(dx*dx + dy*dy);
  }
  float dx_close = points[0][0] - points[points.length-1][0];
  float dy_close = points[0][1] - points[points.length-1][1];
  perimeter = s_arc[points.length-1] + sqrt(dx_close*dx_close + dy_close*dy_close);

  int n_cycles = round(perimeter / LAMBDA_TEX);
  if (n_cycles < 1) n_cycles = 1;
  lambda_actual = perimeter / n_cycles;
  println("Perimeter: " + perimeter + " m, " + n_cycles + " texture cycles, " +
          "lambda = " + lambda_actual + " m");
}


// =============================================================
// SERIAL
// =============================================================
void setupSerial() {
  if (STANDALONE_MODE) return;
  String[] ports = Serial.list();
  println("Available serial ports:");
  for (int i = 0; i < ports.length; i++) {
    println("  [" + i + "] " + ports[i]);
  }

  // Connect to Board 5 ONLY — hardcode the port name
  String BOARD5_PORT = "/dev/cu.usbserial-A10POSFY";  // ← change this to whatever Board 5 is

  try {
    Serial board5 = new Serial(this, BOARD5_PORT, 115200);
    arduinoPorts = new Serial[]{ board5 };
    println("Connected to Board 5 on " + BOARD5_PORT);
  } catch (Exception e) {
    println("Failed to connect: " + e.getMessage());
    STANDALONE_MODE = true;
  }
}
// =============================================================
// VISUAL RENDERING
// =============================================================
float meterToPixelX(float xm) { return ORIGIN_X + xm * PIXELS_PER_METER; }
float meterToPixelY(float ym) { return ORIGIN_Y - ym * PIXELS_PER_METER; }


void drawPenTip(float xh, float yh) {
  noStroke();
  fill(255, 100, 150);
  ellipse(meterToPixelX(xh), meterToPixelY(yh), 12, 12);
}

// Draw the firmware's square outline (where forces are computed against)
// in physical coords, accounting for WORKSPACE_CENTER offset.
// Vertices must match SHAPE_PTS in the firmware exactly (physical meters).
// Closed polygon — last vertex connects back to first.
float[][] FIRMWARE_SHAPE_PTS = {
  { -0.03f, 0.07f },
  {  0.03f, 0.07f },
  {  0.03f, 0.13f },
  { -0.03f, 0.13f }
};

// Draw the polygon outline the firmware is computing forces against.
// Drawn in physical coords, offset by WORKSPACE_CENTER to match the pen.
void drawFirmwareSquare() {
  stroke(0, 200, 100, 150);   // green outline
  strokeWeight(2);
  noFill();

  beginShape();
  for (int i = 0; i < FIRMWARE_SHAPE_PTS.length; i++) {
    float xm = FIRMWARE_SHAPE_PTS[i][0] - WORKSPACE_CENTER_X;
    float ym = FIRMWARE_SHAPE_PTS[i][1] - WORKSPACE_CENTER_Y;
    vertex(meterToPixelX(xm), meterToPixelY(ym));
  }
  endShape(CLOSE);   // closes the polygon
}

// Draw an arrow from pen tip showing force vector.
// Force is in Newtons; we scale it for visibility.
void drawForceVector(float xh_screen, float yh_screen) {
  float fmag = sqrt(arduinoForceX*arduinoForceX + arduinoForceY*arduinoForceY);
  if (fmag < 1e-4f) return;

  // Scale: 1 N -> 50 pixels (tweak if arrow is too big/small)
  float SCALE_PX_PER_N = 50.0f;

  float startX = meterToPixelX(xh_screen);
  float startY = meterToPixelY(yh_screen);
  // Note: meterToPixelY flips y (screen y grows downward), so y-component
  // of force must be flipped too for the arrow direction to be correct.
  float endX = startX - arduinoForceX * SCALE_PX_PER_N;
  float endY = startY + arduinoForceY * SCALE_PX_PER_N;

  stroke(255, 50, 50, 200);
  strokeWeight(3);
  line(startX, startY, endX, endY);

  // Simple arrowhead
  float ang = atan2(endY - startY, endX - startX);
  float ah = 8;
  line(endX, endY, endX - ah*cos(ang - PI/6), endY - ah*sin(ang - PI/6));
  line(endX, endY, endX - ah*cos(ang + PI/6), endY - ah*sin(ang + PI/6));
}

void drawDots() {
  fill(red(dotColor), green(dotColor), blue(dotColor), dotOpacity);
    noStroke();
    for (int i = 0; i < points.length; i++) {
      ellipse(points[i][0], points[i][1], dotRadius * 2, dotRadius * 2);
    }
}

void drawLines() {
    strokeWeight(lineWeight);
    stroke(red(lineColor), green(lineColor), blue(lineColor), lineOpacity);
    noFill();
    for (int i = 0; i < points.length - 1; i++) {
      line(points[i][0], points[i][1], points[i+1][0], points[i+1][1]);
    }
}

void setupShapeDropdown() {
  String[][] shapeList = getShapeList();
  String[] names = new String[shapeList.length];
  int[] ids = new int[shapeList.length];

  for (int i = 0; i < shapeList.length; i++) {
    ids[i] = int(shapeList[i][0]);
    names[i] = shapeList[i][1];
  }

  shapeDropdown = new Dropdown(20, 20, 200, 30, names, ids);
  
}
// Point-in-polygon test using loaded shape points (pixel coords)
boolean pointInShape(float px, float py) {
  if (points == null || points.length < 3) return false;
  boolean inside = false;
  for (int i = 0, j = points.length - 1; i < points.length; j = i++) {
    float xi = points[i][0], yi = points[i][1];
    float xj = points[j][0], yj = points[j][1];
    boolean crosses = ((yi > py) != (yj > py)) &&
                      (px < (xj - xi) * (py - yi) / (yj - yi) + xi);
    if (crosses) inside = !inside;
  }
  return inside;
}

// Nearest point on shape boundary (pixel coords)
float[] nearestOnShape(float px, float py) {
  float bestD2 = 1e30f;
  float[] result = {px, py};
  for (int i = 0; i < points.length - 1; i++) {
    float ax = points[i][0], ay = points[i][1];
    float bx = points[i+1][0], by = points[i+1][1];
    float vx = bx-ax, vy = by-ay;
    float len2 = vx*vx + vy*vy;
    if (len2 < 1e-6f) continue;
    float t = ((px-ax)*vx + (py-ay)*vy) / len2;
    t = constrain(t, 0, 1);
    float nx = ax+t*vx, ny = ay+t*vy;
    float d2 = (px-nx)*(px-nx) + (py-ny)*(py-ny);
    if (d2 < bestD2) { bestD2 = d2; result[0] = nx; result[1] = ny; }
  }
  return result;
}

//void drawPenAndProxy(float xh_m, float yh_m) {
//  float penPx = meterToPixelX(xh_m);
//  float penPy = meterToPixelY(yh_m);

//  if (points != null && points.length > 0 && pointInShape(penPx, penPy)) {
//    float[] proxy = nearestOnShape(penPx, penPy);

//    // Spring line between pen and proxy
//    stroke(150, 150, 255, 180);
//    strokeWeight(1.5f);
//    line(penPx, penPy, proxy[0], proxy[1]);

//    // Proxy dot on boundary (blue)
//    noStroke();
//    fill(50, 100, 255);
//    ellipse(proxy[0], proxy[1], 10, 10);
//  }

//  // Pen tip (pink, always on top)
//  noStroke();
//  fill(255, 100, 150);
//  ellipse(penPx, penPy, 12, 12);
//}

// Line segment intersection in pixel coords
// Returns {t_pen, t_seg} or null if no intersection
float[] segCross(float px, float py, float qx, float qy,
                 float ax, float ay, float bx, float by) {
  float dqx = qx-px, dqy = qy-py;
  float dbx = bx-ax, dby = by-ay;
  float denom = dqx*dby - dqy*dbx;
  if (abs(denom) < 1e-6f) return null;
  float dpx = ax-px, dpy = ay-py;
  float t_pen = (dpx*dby - dpy*dbx) / denom;
  float t_seg = (dpx*dqy - dpy*dqx) / denom;
  if (t_pen >= -0.01f && t_pen <= 1.01f && t_seg >= 0 && t_seg <= 1)
    return new float[]{t_pen, t_seg};
  return null;
}

void updateProcessingProxy(float penPx, float penPy) {
  boolean inside = pointInShape(penPx, penPy);

  if (!inside) {
    proc_was_inside = false;
    // Track nearest segment while outside
    float bestD2 = 1e30f;
    for (int i = 0; i < points.length - 1; i++) {
      float ax = points[i][0], ay = points[i][1];
      float bx = points[i+1][0], by = points[i+1][1];
      float vx = bx-ax, vy = by-ay;
      float len2 = vx*vx + vy*vy;
      if (len2 < 1e-6f) continue;
      float t = ((penPx-ax)*vx + (penPy-ay)*vy) / len2;
      t = constrain(t, 0, 1);
      float nx = ax+t*vx, ny = ay+t*vy;
      float d2 = (penPx-nx)*(penPx-nx) + (penPy-ny)*(penPy-ny);
      if (d2 < bestD2) {
        bestD2 = d2;
        proc_proxy_seg = i;
        proc_proxy_t   = t;
      }
    }
    // Proxy follows pen outside
    proc_proxy_px = penPx;
    proc_proxy_py = penPy;
    return;
  }

  // Inside
  if (!proc_was_inside) {
    // Find crossing segment
    float bestTPen = 1e30f;
    for (int i = 0; i < points.length - 1; i++) {
      float[] hit = segCross(pen_px_prev, pen_py_prev, penPx, penPy,
                             points[i][0], points[i][1],
                             points[i+1][0], points[i+1][1]);
      if (hit != null && hit[0] < bestTPen) {
        bestTPen = hit[0];
        proc_proxy_seg = i;
        proc_proxy_t   = hit[1];
      }
    }
    proc_was_inside = true;
  }

  // Slide proxy along adjacent segments only
  float ax = points[proc_proxy_seg][0], ay = points[proc_proxy_seg][1];
  int nextSeg = (proc_proxy_seg + 1) % (points.length - 1);
  float bx = points[nextSeg][0], by = points[nextSeg][1];
  float tx = bx-ax, ty = by-ay;
  float len2 = tx*tx + ty*ty;

  if (len2 > 1e-6f) {
    float dx = penPx - proc_proxy_px;
    float dy = penPy - proc_proxy_py;
    float delta_t = (dx*tx + dy*ty) / len2;
    delta_t = constrain(delta_t, -0.5f, 0.5f);
    float new_t = proc_proxy_t + delta_t;

    if (new_t >= 1.0f) {
      proc_proxy_seg = nextSeg;
      proc_proxy_t   = 0.0f;
    } else if (new_t <= 0.0f) {
      proc_proxy_seg = (proc_proxy_seg - 1 + (points.length-1)) % (points.length-1);
      proc_proxy_t   = 1.0f;
    } else {
      proc_proxy_t = new_t;
    }
  }

  // Compute proxy pixel position
  ax = points[proc_proxy_seg][0]; ay = points[proc_proxy_seg][1];
  nextSeg = (proc_proxy_seg + 1) % (points.length - 1);
  bx = points[nextSeg][0]; by = points[nextSeg][1];
  proc_proxy_px = ax + proc_proxy_t * (bx - ax);
  proc_proxy_py = ay + proc_proxy_t * (by - ay);
}

void drawPenAndProxy(float xh_m, float yh_m) {
  float penPx = meterToPixelX(xh_m);
  float penPy = meterToPixelY(yh_m);

  updateProcessingProxy(penPx, penPy);

  // Save for next frame's crossing detection
  pen_px_prev = penPx;
  pen_py_prev = penPy;

  // Blue dot = proxy position (on boundary when inside, pen when outside)
  noStroke();
  fill(50, 100, 255);
  ellipse(proc_proxy_px, proc_proxy_py, 14, 14);
}


void drawGuessSidebar() {
  int panelX = 650;
  int panelY = 80;
  int panelW = 220;
  int entryH = 38;
  int gap = 8;
  int cornerR = 10;

  // Panel header
  fill(60);
  textAlign(LEFT, TOP);
  textSize(13);
  text("Recent guesses", panelX, panelY - 22);

  if (recentGuesses.length == 0) {
    fill(160);
    textSize(12);
    text("No guesses yet", panelX, panelY + 6);
    return;
  }

  for (int i = 0; i < recentGuesses.length; i++) {
    int cardY = panelY + i * (entryH + gap);

    // Alternating soft background
    if (i % 2 == 0) fill(253, 240, 248, 220);  // soft pink
    else            fill(245, 242, 255, 220);   // soft lavender

    noStroke();
    rect(panelX, cardY, panelW, entryH, cornerR);

    // Guess number badge
    fill(180, 140, 200);
    ellipse(panelX + 18, cardY + entryH / 2, 20, 20);
    fill(255);
    textAlign(CENTER, CENTER);
    textSize(10);
    text(i + 1, panelX + 18, cardY + entryH / 2);

    // Guess text — truncate if too long
    fill(50);
    textAlign(LEFT, CENTER);
    textSize(12);
    String label = recentGuesses[i];
    if (label.length() > 22) label = label.substring(0, 20) + "…";
    text(label, panelX + 34, cardY + entryH / 2);
  }
  
  textAlign(LEFT, TOP); // reset
}

void serialEvent(Serial p) {
  String raw = p.readStringUntil('\n');
  if (raw == null) return;
  raw = raw.trim();

  String[] parts = splitTokens(raw, ", \t");
  if (parts.length >= 4) {
    try {
      float xh = Float.parseFloat(parts[0]);
      float yh = Float.parseFloat(parts[1]);
      float fx = Float.parseFloat(parts[2]);
      float fy = Float.parseFloat(parts[3]);
      arduinoFx = xh;
      arduinoFy = yh;
      arduinoForceX = fx;
      arduinoForceY = fy;
    } catch (Exception e) {
      // Bad packet — ignore silently (most are # debug lines from board 1)
    }
  } else if (parts.length >= 2) {
    // Backward compat: pre-step-2 firmware sent only xh, yh
    try {
      arduinoFx = Float.parseFloat(parts[0]);
      arduinoFy = Float.parseFloat(parts[1]);
    } catch (Exception e) {}
  }
}
