// ============================================================
// ME327 Team 10 - Force Model Tester (Processing)
// ============================================================
// Multi-shape version. Three shapes (bunny, hammer, pear) derived from
// the same Python-generated CSVs that feed the Arduino code.
//
// Two modes:
//   STANDALONE  : compute the force model in Processing itself
//                 (no Arduino needed -- fastest way to validate the math)
//   HARDWARE    : stream mouse position to an Arduino over serial,
//                 receive force back, render it
//
// Visual:
//   - Black outline = active shape
//   - Light blue band = dead zone (P_T < d < 0, F = 0)
//   - Light red band = guidance region (d < P_T, exponential pull)
//   - Pink dot = mouse / pen-tip position
//   - Green arrow = force vector on the user
//   - Top-left HUD: shape, mode, depth, force
//
// Controls:
//   B / H / P keys : switch to Bunny / Hammer / Pear
//   T key          : toggle MODE_CONTROL <-> MODE_TEXTURED
//   M key          : toggle STANDALONE <-> HARDWARE
//   R key          : reset velocity state
// ============================================================

import processing.serial.*;

// ---------- MODE SELECTION ----------
boolean STANDALONE_MODE = true;
String SERIAL_PORT_NAME = "";       // auto-detect first port if blank

// ---------- RENDERING CONDITION ----------
boolean texturedMode = true;


// ---------- PHYSICAL <-> SCREEN MAPPING ----------
float PIXELS_PER_METER = 4000.0f;
float ORIGIN_X, ORIGIN_Y;


// ---------- FORCE MODEL PARAMETERS (must match .ino) ----------
float K_WALL       = 2000.0f;
float B_WALL       = 15.0f;
float P_T          = -0.003f;
float A_GUIDE      = 0.5f;
float C_GUIDE      = 200.0f;
float F_GUIDE_MAX  = 2.0f;
float A_TEX        = 0.30f;
float LAMBDA_TEX   = 0.0020f;


// ---------- SHAPE DATA (must match .ino) ----------
// Three shapes, each 200 points, CCW, normalized to fit ~7 cm bounding box.
// Auto-generated by preprocess_shapes.py from the team's SVG-derived CSVs.

float[][] shape_bunny = {
    {  0.00326f,  0.03500f},
    {  0.00202f,  0.03450f},
    { -0.00191f,  0.03176f},
    { -0.00719f,  0.02827f},
    { -0.01005f,  0.02560f},
    { -0.01059f,  0.02518f},
    { -0.01076f,  0.02501f},
    { -0.01085f,  0.02491f},
    { -0.01092f,  0.02485f},
    { -0.01099f,  0.02485f},
    { -0.01105f,  0.02485f},
    { -0.01110f,  0.02485f},
    { -0.01115f,  0.02485f},
    { -0.01119f,  0.02485f},
    { -0.01122f,  0.02487f},
    { -0.01125f,  0.02489f},
    { -0.01128f,  0.02492f},
    { -0.01131f,  0.02495f},
    { -0.01135f,  0.02499f},
    { -0.01133f,  0.02502f},
    { -0.01130f,  0.02507f},
    { -0.01125f,  0.02512f},
    { -0.01121f,  0.02520f},
    { -0.01121f,  0.02534f},
    { -0.01121f,  0.02561f},
    { -0.01091f,  0.02685f},
    { -0.01091f,  0.02782f},
    { -0.01121f,  0.02884f},
    { -0.01151f,  0.02952f},
    { -0.01193f,  0.03005f},
    { -0.01224f,  0.03050f},
    { -0.01276f,  0.03067f},
    { -0.01347f,  0.03097f},
    { -0.01421f,  0.03112f},
    { -0.01494f,  0.03097f},
    { -0.01577f,  0.03082f},
    { -0.01647f,  0.03049f},
    { -0.01696f,  0.03015f},
    { -0.01733f,  0.02972f},
    { -0.01763f,  0.02891f},
    { -0.01887f,  0.02511f},
    { -0.01972f,  0.02208f},
    { -0.01989f,  0.02170f},
    { -0.02002f,  0.02146f},
    { -0.02017f,  0.02127f},
    { -0.02037f,  0.02112f},
    { -0.02069f,  0.02112f},
    { -0.02143f,  0.02112f},
    { -0.02465f,  0.02067f},
    { -0.02781f,  0.01963f},
    { -0.02899f,  0.01901f},
    { -0.02967f,  0.01833f},
    { -0.03025f,  0.01760f},
    { -0.03061f,  0.01692f},
    { -0.03091f,  0.01522f},
    { -0.03166f,  0.01269f},
    { -0.03219f,  0.00955f},
    { -0.03283f,  0.00518f},
    { -0.03326f,  0.00265f},
    { -0.03315f,  0.00184f},
    { -0.03300f,  0.00105f},
    { -0.03238f, -0.00009f},
    { -0.03163f, -0.00114f},
    { -0.03086f, -0.00176f},
    { -0.02956f, -0.00247f},
    { -0.02710f, -0.00320f},
    { -0.02648f, -0.00335f},
    { -0.02621f, -0.00343f},
    { -0.02601f, -0.00351f},
    { -0.02585f, -0.00365f},
    { -0.02584f, -0.00388f},
    { -0.02584f, -0.00422f},
    { -0.02584f, -0.00581f},
    { -0.02554f, -0.00741f},
    { -0.02462f, -0.00949f},
    { -0.02392f, -0.01140f},
    { -0.02335f, -0.01256f},
    { -0.02262f, -0.01344f},
    { -0.02013f, -0.01589f},
    { -0.01880f, -0.01680f},
    { -0.01556f, -0.01825f},
    { -0.01491f, -0.01843f},
    { -0.01470f, -0.01852f},
    { -0.01457f, -0.01858f},
    { -0.01446f, -0.01862f},
    { -0.01437f, -0.01870f},
    { -0.01435f, -0.01880f},
    { -0.01435f, -0.01891f},
    { -0.01437f, -0.01904f},
    { -0.01449f, -0.01917f},
    { -0.01470f, -0.01938f},
    { -0.01527f, -0.02054f},
    { -0.01554f, -0.02101f},
    { -0.01554f, -0.02146f},
    { -0.01554f, -0.02189f},
    { -0.01539f, -0.02228f},
    { -0.01515f, -0.02270f},
    { -0.01427f, -0.02350f},
    { -0.01385f, -0.02385f},
    { -0.01368f, -0.02402f},
    { -0.01356f, -0.02414f},
    { -0.01346f, -0.02425f},
    { -0.01346f, -0.02438f},
    { -0.01355f, -0.02450f},
    { -0.01368f, -0.02463f},
    { -0.01390f, -0.02485f},
    { -0.01478f, -0.02575f},
    { -0.01539f, -0.02725f},
    { -0.01570f, -0.02843f},
    { -0.01584f, -0.02922f},
    { -0.01574f, -0.02987f},
    { -0.01552f, -0.03053f},
    { -0.01519f, -0.03116f},
    { -0.01468f, -0.03167f},
    { -0.01410f, -0.03210f},
    { -0.01354f, -0.03237f},
    { -0.01276f, -0.03246f},
    { -0.01035f, -0.03246f},
    { -0.00729f, -0.03186f},
    { -0.00584f, -0.03140f},
    { -0.00551f, -0.03126f},
    { -0.00520f, -0.03130f},
    { -0.00495f, -0.03155f},
    { -0.00450f, -0.03186f},
    { -0.00258f, -0.03377f},
    { -0.00146f, -0.03444f},
    { -0.00051f, -0.03484f},
    {  0.00073f, -0.03500f},
    {  0.00185f, -0.03499f},
    {  0.00493f, -0.03422f},
    {  0.01140f, -0.03260f},
    {  0.01569f, -0.03186f},
    {  0.01749f, -0.03136f},
    {  0.01837f, -0.03078f},
    {  0.01968f, -0.02971f},
    {  0.02126f, -0.02729f},
    {  0.02228f, -0.02583f},
    {  0.02276f, -0.02535f},
    {  0.02315f, -0.02514f},
    {  0.02369f, -0.02499f},
    {  0.02629f, -0.02450f},
    {  0.02773f, -0.02396f},
    {  0.02899f, -0.02314f},
    {  0.03126f, -0.02117f},
    {  0.03192f, -0.02035f},
    {  0.03281f, -0.01841f},
    {  0.03317f, -0.01703f},
    {  0.03326f, -0.01575f},
    {  0.03311f, -0.01462f},
    {  0.03268f, -0.01352f},
    {  0.03234f, -0.01273f},
    {  0.03171f, -0.01210f},
    {  0.03085f, -0.01154f},
    {  0.02987f, -0.01111f},
    {  0.02960f, -0.01103f},
    {  0.02943f, -0.01086f},
    {  0.02938f, -0.01063f},
    {  0.02938f, -0.01027f},
    {  0.02923f, -0.00832f},
    {  0.02938f, -0.00637f},
    {  0.02878f, -0.00394f},
    {  0.02813f, -0.00136f},
    {  0.02640f,  0.00196f},
    {  0.02454f,  0.00432f},
    {  0.02133f,  0.00738f},
    {  0.01824f,  0.00913f},
    {  0.01556f,  0.01016f},
    {  0.01344f,  0.01052f},
    {  0.01095f,  0.01060f},
    {  0.00341f,  0.00917f},
    { -0.00027f,  0.00829f},
    { -0.00106f,  0.00830f},
    { -0.00218f,  0.00865f},
    { -0.00483f,  0.00963f},
    { -0.00679f,  0.00983f},
    { -0.00733f,  0.00994f},
    { -0.00771f,  0.01015f},
    { -0.00802f,  0.01061f},
    { -0.00868f,  0.01152f},
    { -0.00928f,  0.01277f},
    { -0.00972f,  0.01403f},
    { -0.00972f,  0.01476f},
    { -0.00972f,  0.01526f},
    { -0.00956f,  0.01561f},
    { -0.00938f,  0.01594f},
    { -0.00902f,  0.01629f},
    { -0.00656f,  0.01786f},
    { -0.00207f,  0.02042f},
    {  0.00367f,  0.02321f},
    {  0.00476f,  0.02397f},
    {  0.00579f,  0.02500f},
    {  0.00625f,  0.02585f},
    {  0.00655f,  0.02675f},
    {  0.00670f,  0.02782f},
    {  0.00655f,  0.02961f},
    {  0.00587f,  0.03210f},
    {  0.00550f,  0.03295f},
    {  0.00437f,  0.03435f},
    {  0.00387f,  0.03483f},
    {  0.00326f,  0.03500f}
};

float[][] shape_hammer = {
    {  0.01862f, -0.01738f},
    {  0.01907f, -0.01753f},
    {  0.01996f, -0.01752f},
    {  0.02045f, -0.01750f},
    {  0.02080f, -0.01742f},
    {  0.02133f, -0.01720f},
    {  0.02349f, -0.01627f},
    {  0.02469f, -0.01556f},
    {  0.02613f, -0.01452f},
    {  0.02763f, -0.01317f},
    {  0.02898f, -0.01170f},
    {  0.03002f, -0.01029f},
    {  0.03091f, -0.00878f},
    {  0.03168f, -0.00712f},
    {  0.03227f, -0.00537f},
    {  0.03282f, -0.00292f},
    {  0.03316f, -0.00041f},
    {  0.03319f,  0.00062f},
    {  0.03313f,  0.00129f},
    {  0.03303f,  0.00183f},
    {  0.03287f,  0.00234f},
    {  0.03262f,  0.00293f},
    {  0.03187f,  0.00428f},
    {  0.03165f,  0.00473f},
    {  0.03155f,  0.00500f},
    {  0.03150f,  0.00531f},
    {  0.03149f,  0.00590f},
    {  0.03150f,  0.00663f},
    {  0.03155f,  0.00703f},
    {  0.03163f,  0.00730f},
    {  0.03174f,  0.00757f},
    {  0.03187f,  0.00783f},
    {  0.03201f,  0.00806f},
    {  0.03218f,  0.00828f},
    {  0.03244f,  0.00852f},
    {  0.03304f,  0.00898f},
    {  0.03392f,  0.00956f},
    {  0.03407f,  0.00970f},
    {  0.03417f,  0.00983f},
    {  0.03426f,  0.00996f},
    {  0.03434f,  0.01014f},
    {  0.03444f,  0.01042f},
    {  0.03457f,  0.01106f},
    {  0.03495f,  0.01388f},
    {  0.03500f,  0.01427f},
    {  0.03500f,  0.01447f},
    {  0.03497f,  0.01464f},
    {  0.03491f,  0.01481f},
    {  0.03482f,  0.01501f},
    {  0.03467f,  0.01526f},
    {  0.03446f,  0.01556f},
    {  0.03418f,  0.01586f},
    {  0.03391f,  0.01612f},
    {  0.03367f,  0.01630f},
    {  0.03343f,  0.01645f},
    {  0.03315f,  0.01658f},
    {  0.03279f,  0.01670f},
    {  0.03214f,  0.01683f},
    {  0.02777f,  0.01737f},
    {  0.02627f,  0.01753f},
    {  0.02605f,  0.01753f},
    {  0.02594f,  0.01751f},
    {  0.02586f,  0.01748f},
    {  0.02579f,  0.01745f},
    {  0.02573f,  0.01742f},
    {  0.02566f,  0.01738f},
    {  0.02559f,  0.01733f},
    {  0.02553f,  0.01727f},
    {  0.02546f,  0.01718f},
    {  0.02538f,  0.01706f},
    {  0.02531f,  0.01686f},
    {  0.02522f,  0.01647f},
    {  0.02507f,  0.01537f},
    {  0.02468f,  0.01196f},
    {  0.02468f,  0.01158f},
    {  0.02470f,  0.01137f},
    {  0.02474f,  0.01121f},
    {  0.02480f,  0.01107f},
    {  0.02488f,  0.01092f},
    {  0.02505f,  0.01070f},
    {  0.02585f,  0.00981f},
    {  0.02618f,  0.00937f},
    {  0.02636f,  0.00905f},
    {  0.02648f,  0.00875f},
    {  0.02657f,  0.00845f},
    {  0.02663f,  0.00811f},
    {  0.02667f,  0.00774f},
    {  0.02666f,  0.00736f},
    {  0.02662f,  0.00700f},
    {  0.02654f,  0.00666f},
    {  0.02643f,  0.00633f},
    {  0.02627f,  0.00600f},
    {  0.02607f,  0.00567f},
    {  0.02582f,  0.00534f},
    {  0.02556f,  0.00506f},
    {  0.02533f,  0.00485f},
    {  0.02511f,  0.00470f},
    {  0.02491f,  0.00458f},
    {  0.02469f,  0.00448f},
    {  0.02444f,  0.00441f},
    {  0.02412f,  0.00435f},
    {  0.02366f,  0.00431f},
    {  0.02272f,  0.00435f},
    {  0.00493f,  0.00656f},
    { -0.01013f,  0.00844f},
    { -0.01043f,  0.00848f},
    { -0.01061f,  0.00850f},
    { -0.01074f,  0.00852f},
    { -0.01086f,  0.00853f},
    { -0.01095f,  0.00856f},
    { -0.01098f,  0.00867f},
    { -0.01101f,  0.00881f},
    { -0.01118f,  0.00917f},
    { -0.01132f,  0.00931f},
    { -0.01146f,  0.00942f},
    { -0.01163f,  0.00952f},
    { -0.01185f,  0.00962f},
    { -0.01216f,  0.00971f},
    { -0.01260f,  0.00980f},
    { -0.02337f,  0.01115f},
    { -0.03023f,  0.01199f},
    { -0.03087f,  0.01220f},
    { -0.03137f,  0.01244f},
    { -0.03161f,  0.01250f},
    { -0.03182f,  0.01251f},
    { -0.03202f,  0.01251f},
    { -0.03224f,  0.01247f},
    { -0.03248f,  0.01242f},
    { -0.03274f,  0.01233f},
    { -0.03301f,  0.01220f},
    { -0.03327f,  0.01205f},
    { -0.03351f,  0.01187f},
    { -0.03372f,  0.01168f},
    { -0.03387f,  0.01150f},
    { -0.03397f,  0.01134f},
    { -0.03404f,  0.01121f},
    { -0.03411f,  0.01102f},
    { -0.03425f,  0.01046f},
    { -0.03486f,  0.00660f},
    { -0.03500f,  0.00495f},
    { -0.03500f,  0.00466f},
    { -0.03498f,  0.00447f},
    { -0.03493f,  0.00425f},
    { -0.03483f,  0.00402f},
    { -0.03471f,  0.00378f},
    { -0.03458f,  0.00357f},
    { -0.03444f,  0.00339f},
    { -0.03428f,  0.00324f},
    { -0.03413f,  0.00311f},
    { -0.03397f,  0.00300f},
    { -0.03379f,  0.00291f},
    { -0.03360f,  0.00284f},
    { -0.03337f,  0.00278f},
    { -0.03307f,  0.00275f},
    { -0.03244f,  0.00276f},
    { -0.03044f,  0.00267f},
    { -0.01398f,  0.00064f},
    { -0.01334f,  0.00060f},
    { -0.01318f,  0.00061f},
    { -0.01299f,  0.00062f},
    { -0.01279f,  0.00066f},
    { -0.01259f,  0.00073f},
    { -0.01237f,  0.00085f},
    { -0.01199f,  0.00124f},
    { -0.01188f,  0.00140f},
    { -0.01180f,  0.00151f},
    { -0.01170f,  0.00152f},
    { -0.01158f,  0.00151f},
    { -0.01144f,  0.00149f},
    { -0.01126f,  0.00146f},
    { -0.01092f,  0.00142f},
    {  0.01008f, -0.00123f},
    {  0.02054f, -0.00257f},
    {  0.02125f, -0.00274f},
    {  0.02170f, -0.00291f},
    {  0.02207f, -0.00309f},
    {  0.02241f, -0.00331f},
    {  0.02276f, -0.00360f},
    {  0.02312f, -0.00394f},
    {  0.02342f, -0.00431f},
    {  0.02367f, -0.00469f},
    {  0.02387f, -0.00508f},
    {  0.02403f, -0.00549f},
    {  0.02415f, -0.00591f},
    {  0.02423f, -0.00636f},
    {  0.02425f, -0.00684f},
    {  0.02423f, -0.00729f},
    {  0.02416f, -0.00772f},
    {  0.02399f, -0.00835f},
    {  0.02362f, -0.00932f},
    {  0.02290f, -0.01075f},
    {  0.02167f, -0.01269f},
    {  0.01988f, -0.01495f},
    {  0.01894f, -0.01601f},
    {  0.01876f, -0.01625f},
    {  0.01867f, -0.01642f},
    {  0.01861f, -0.01661f},
    {  0.01858f, -0.01683f},
    {  0.01858f, -0.01710f},
    {  0.01862f, -0.01738f}
};

float[][] shape_pear = {
    { -0.00260f,  0.03430f},
    { -0.00336f,  0.03467f},
    { -0.00374f,  0.03481f},
    { -0.00409f,  0.03490f},
    { -0.00450f,  0.03496f},
    { -0.00522f,  0.03500f},
    { -0.01113f,  0.03476f},
    { -0.01392f,  0.03469f},
    { -0.01435f,  0.03465f},
    { -0.01458f,  0.03461f},
    { -0.01473f,  0.03457f},
    { -0.01483f,  0.03453f},
    { -0.01491f,  0.03449f},
    { -0.01497f,  0.03445f},
    { -0.01502f,  0.03441f},
    { -0.01506f,  0.03437f},
    { -0.01510f,  0.03433f},
    { -0.01513f,  0.03429f},
    { -0.01516f,  0.03425f},
    { -0.01518f,  0.03420f},
    { -0.01520f,  0.03414f},
    { -0.01522f,  0.03408f},
    { -0.01523f,  0.03400f},
    { -0.01524f,  0.03391f},
    { -0.01523f,  0.03379f},
    { -0.01521f,  0.03363f},
    { -0.01516f,  0.03338f},
    { -0.01501f,  0.03291f},
    { -0.01428f,  0.03123f},
    { -0.01276f,  0.02812f},
    { -0.01224f,  0.02727f},
    { -0.01177f,  0.02664f},
    { -0.01113f,  0.02593f},
    { -0.01046f,  0.02530f},
    { -0.00986f,  0.02483f},
    { -0.00925f,  0.02445f},
    { -0.00864f,  0.02413f},
    { -0.00803f,  0.02387f},
    { -0.00742f,  0.02368f},
    { -0.00681f,  0.02355f},
    { -0.00621f,  0.02348f},
    { -0.00561f,  0.02346f},
    { -0.00503f,  0.02349f},
    { -0.00445f,  0.02357f},
    { -0.00389f,  0.02370f},
    { -0.00334f,  0.02389f},
    { -0.00280f,  0.02412f},
    { -0.00223f,  0.02444f},
    { -0.00111f,  0.02522f},
    { -0.00076f,  0.02542f},
    { -0.00056f,  0.02552f},
    { -0.00042f,  0.02556f},
    { -0.00032f,  0.02559f},
    { -0.00024f,  0.02560f},
    { -0.00017f,  0.02561f},
    { -0.00011f,  0.02561f},
    { -0.00005f,  0.02560f},
    { -0.00000f,  0.02559f},
    {  0.00004f,  0.02557f},
    {  0.00009f,  0.02555f},
    {  0.00013f,  0.02553f},
    {  0.00018f,  0.02550f},
    {  0.00022f,  0.02546f},
    {  0.00027f,  0.02541f},
    {  0.00032f,  0.02535f},
    {  0.00038f,  0.02527f},
    {  0.00044f,  0.02515f},
    {  0.00051f,  0.02497f},
    {  0.00060f,  0.02469f},
    {  0.00071f,  0.02423f},
    {  0.00079f,  0.02377f},
    {  0.00083f,  0.02348f},
    {  0.00085f,  0.02330f},
    {  0.00085f,  0.02320f},
    {  0.00084f,  0.02313f},
    {  0.00083f,  0.02307f},
    {  0.00081f,  0.02303f},
    {  0.00079f,  0.02299f},
    {  0.00076f,  0.02296f},
    {  0.00073f,  0.02292f},
    {  0.00068f,  0.02289f},
    {  0.00063f,  0.02285f},
    {  0.00055f,  0.02281f},
    {  0.00043f,  0.02277f},
    {  0.00023f,  0.02271f},
    { -0.00017f,  0.02264f},
    { -0.00136f,  0.02245f},
    { -0.00199f,  0.02229f},
    { -0.00263f,  0.02206f},
    { -0.00328f,  0.02177f},
    { -0.00395f,  0.02138f},
    { -0.00465f,  0.02089f},
    { -0.00539f,  0.02027f},
    { -0.00619f,  0.01946f},
    { -0.00707f,  0.01840f},
    { -0.00805f,  0.01698f},
    { -0.00917f,  0.01503f},
    { -0.01045f,  0.01227f},
    { -0.01211f,  0.00771f},
    { -0.01293f,  0.00570f},
    { -0.01384f,  0.00397f},
    { -0.01633f,  0.00011f},
    { -0.01992f, -0.00522f},
    { -0.02118f, -0.00752f},
    { -0.02197f, -0.00932f},
    { -0.02250f, -0.01089f},
    { -0.02286f, -0.01238f},
    { -0.02309f, -0.01390f},
    { -0.02319f, -0.01557f},
    { -0.02314f, -0.01731f},
    { -0.02296f, -0.01889f},
    { -0.02265f, -0.02043f},
    { -0.02220f, -0.02195f},
    { -0.02162f, -0.02343f},
    { -0.02090f, -0.02486f},
    { -0.02005f, -0.02624f},
    { -0.01907f, -0.02757f},
    { -0.01796f, -0.02882f},
    { -0.01673f, -0.02998f},
    { -0.01538f, -0.03105f},
    { -0.01392f, -0.03201f},
    { -0.01236f, -0.03286f},
    { -0.01070f, -0.03358f},
    { -0.00895f, -0.03417f},
    { -0.00786f, -0.03443f},
    { -0.00591f, -0.03469f},
    { -0.00016f, -0.03500f},
    {  0.00565f, -0.03492f},
    {  0.00765f, -0.03474f},
    {  0.00846f, -0.03458f},
    {  0.00991f, -0.03416f},
    {  0.01146f, -0.03355f},
    {  0.01302f, -0.03278f},
    {  0.01455f, -0.03185f},
    {  0.01602f, -0.03078f},
    {  0.01739f, -0.02958f},
    {  0.01862f, -0.02829f},
    {  0.01970f, -0.02695f},
    {  0.02060f, -0.02560f},
    {  0.02134f, -0.02427f},
    {  0.02192f, -0.02296f},
    {  0.02238f, -0.02158f},
    {  0.02284f, -0.01968f},
    {  0.02309f, -0.01808f},
    {  0.02319f, -0.01664f},
    {  0.02315f, -0.01520f},
    {  0.02298f, -0.01363f},
    {  0.02259f, -0.01173f},
    {  0.02181f, -0.00909f},
    {  0.01999f, -0.00442f},
    {  0.01705f,  0.00243f},
    {  0.01491f,  0.00869f},
    {  0.01350f,  0.01264f},
    {  0.01238f,  0.01508f},
    {  0.01147f,  0.01670f},
    {  0.01070f,  0.01782f},
    {  0.01003f,  0.01862f},
    {  0.00945f,  0.01922f},
    {  0.00892f,  0.01966f},
    {  0.00843f,  0.02001f},
    {  0.00797f,  0.02027f},
    {  0.00753f,  0.02047f},
    {  0.00711f,  0.02062f},
    {  0.00631f,  0.02080f},
    {  0.00592f,  0.02089f},
    {  0.00569f,  0.02096f},
    {  0.00552f,  0.02103f},
    {  0.00541f,  0.02110f},
    {  0.00531f,  0.02116f},
    {  0.00524f,  0.02123f},
    {  0.00517f,  0.02130f},
    {  0.00511f,  0.02138f},
    {  0.00505f,  0.02149f},
    {  0.00499f,  0.02166f},
    {  0.00493f,  0.02197f},
    {  0.00475f,  0.02287f},
    {  0.00395f,  0.02741f},
    {  0.00381f,  0.02802f},
    {  0.00365f,  0.02848f},
    {  0.00348f,  0.02886f},
    {  0.00330f,  0.02918f},
    {  0.00312f,  0.02945f},
    {  0.00294f,  0.02966f},
    {  0.00277f,  0.02984f},
    {  0.00260f,  0.02998f},
    {  0.00244f,  0.03010f},
    {  0.00227f,  0.03019f},
    {  0.00208f,  0.03027f},
    {  0.00167f,  0.03036f},
    {  0.00140f,  0.03041f},
    {  0.00125f,  0.03047f},
    {  0.00111f,  0.03056f},
    {  0.00095f,  0.03068f},
    {  0.00075f,  0.03087f},
    {  0.00047f,  0.03119f},
    { -0.00032f,  0.03230f},
    { -0.00082f,  0.03289f},
    { -0.00130f,  0.03337f},
    { -0.00184f,  0.03381f},
    { -0.00260f,  0.03430f}
};

// Active shape (pointer + length).
float[][] shape;
int N_POINTS;
String shapeName;

void setShape(int id) {
  switch (id) {
    case 0: shape = shape_bunny;  shapeName = "BUNNY";  break;
    case 1: shape = shape_hammer; shapeName = "HAMMER"; break;
    case 2: shape = shape_pear;   shapeName = "PEAR";   break;
  }
  N_POINTS = shape.length;
  precomputeArcLength();
  println("Active shape: " + shapeName + " (" + N_POINTS + " pts)");

  // Tell Arduino too, if connected.
  if (arduinoPort != null) {
    if (id == 0)      arduinoPort.write('B');
    else if (id == 1) arduinoPort.write('H');
    else if (id == 2) arduinoPort.write('P');
  }
}


// Precomputed arc-length table (sized for max possible):
float[] s_arc;
float perimeter;
float lambda_actual;


// ---------- VELOCITY TRACKING ----------
float xh_prev = 0, yh_prev = 0;
float vx_filt = 0, vy_filt = 0;
float DT_LOOP = 0.001f;


// ---------- SERIAL ----------
Serial arduinoPort = null;
float arduinoFx = 0, arduinoFy = 0;


// =============================================================
// SETUP
// =============================================================
void setup() {
  size(900, 900);
  ORIGIN_X = width / 2.0f;
  ORIGIN_Y = height / 2.0f;

  setShape(0);   // start with bunny
  setupSerial();
}


// =============================================================
// DRAW LOOP
// =============================================================
void draw() {
  background(245);

  float xh = (mouseX - ORIGIN_X) / PIXELS_PER_METER;
  float yh = -(mouseY - ORIGIN_Y) / PIXELS_PER_METER;

  float vx_raw = (xh - xh_prev) / DT_LOOP;
  float vy_raw = (yh - yh_prev) / DT_LOOP;
  vx_filt = 0.9f * vx_raw + 0.1f * vx_filt;
  vy_filt = 0.9f * vy_raw + 0.1f * vy_filt;
  xh_prev = xh;
  yh_prev = yh;

  float[] F;
  float signedDepth;
  if (STANDALONE_MODE) {
    F = computeForceStandalone(xh, yh);
  } else {
    sendMouseToArduino(xh, yh);
    F = new float[]{arduinoFx, arduinoFy};
    computeForceStandalone(xh, yh);  // also run locally for HUD depth value
  }
  signedDepth = lastSignedDepth;

  drawGuidanceRegion();
  drawDeadZone();
  drawShape();
  drawPenTip(xh, yh);
  drawForceArrow(xh, yh, F[0], F[1]);
  drawHUD(xh, yh, F[0], F[1], signedDepth);
}


// =============================================================
// FORCE MODEL (standalone)
// =============================================================
float lastSignedDepth = 0;

float[] computeForceStandalone(float x, float y) {
  float[] result = findNearestSegment(x, y);
  float unsigned_d = result[0];
  float nx = result[1];
  float ny = result[2];
  float t_frac = result[3];
  int seg_i = (int) result[4];

  boolean inside = isInsidePolygon(x, y);
  float d = inside ? unsigned_d : -unsigned_d;
  lastSignedDepth = d;

  float v_inward = -(vx_filt * nx + vy_filt * ny);

  float Fx = 0, Fy = 0;

  if (d > 0.0f) {
    float F_wall_mag = K_WALL * d;
    if (v_inward > 0.0f) F_wall_mag += B_WALL * v_inward;
    Fx = F_wall_mag * nx;
    Fy = F_wall_mag * ny;

    if (texturedMode) {
      int next_i = (seg_i + 1) % N_POINTS;
      float seg_len = (next_i == 0) ? (perimeter - s_arc[seg_i])
                                    : (s_arc[next_i] - s_arc[seg_i]);
      float s = s_arc[seg_i] + t_frac * seg_len;
      float F_tex = A_TEX * sin(2 * PI * s / lambda_actual);
      Fx += F_tex * nx;
      Fy += F_tex * ny;
    }
  } else if (d > P_T) {
    Fx = 0; Fy = 0;
  } else {
    float F_guide = A_GUIDE * exp(-C_GUIDE * (d - P_T));
    if (F_guide > F_GUIDE_MAX) F_guide = F_GUIDE_MAX;
    Fx = -F_guide * nx;
    Fy = -F_guide * ny;
  }

  return new float[]{Fx, Fy};
}


float[] findNearestSegment(float x, float y) {
  int best_i = 0;
  float best_dist = 1e9f;
  float best_nx = 0, best_ny = 0, best_t = 0;

  for (int i = 0; i < N_POINTS; i++) {
    int j = (i + 1) % N_POINTS;
    float ax = shape[i][0], ay = shape[i][1];
    float bx = shape[j][0], by = shape[j][1];
    float tx = bx - ax;
    float ty = by - ay;
    float seg_len2 = tx*tx + ty*ty;

    float t = ((x - ax)*tx + (y - ay)*ty) / seg_len2;
    if (t < 0) t = 0;
    if (t > 1) t = 1;

    float px = ax + t*tx;
    float py = ay + t*ty;
    float ddx = x - px;
    float ddy = y - py;
    float d = sqrt(ddx*ddx + ddy*ddy);

    if (d < best_dist) {
      best_dist = d;
      best_i = i;
      best_t = t;
      float seg_len = sqrt(seg_len2);
      // Outward normal for a CCW polygon in math (y-up) coords:
      // rotate tangent -90 deg, i.e. (tx, ty) -> (ty, -tx).
      best_nx =  ty / seg_len;
      best_ny = -tx / seg_len;
    }
  }
  return new float[]{best_dist, best_nx, best_ny, best_t, best_i};
}


boolean isInsidePolygon(float x, float y) {
  boolean inside = false;
  for (int i = 0, j = N_POINTS - 1; i < N_POINTS; j = i++) {
    float xi = shape[i][0], yi = shape[i][1];
    float xj = shape[j][0], yj = shape[j][1];
    boolean intersect = ((yi > y) != (yj > y)) &&
                       (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
    if (intersect) inside = !inside;
  }
  return inside;
}


void precomputeArcLength() {
  s_arc = new float[N_POINTS];
  s_arc[0] = 0;
  for (int i = 1; i < N_POINTS; i++) {
    float dx = shape[i][0] - shape[i-1][0];
    float dy = shape[i][1] - shape[i-1][1];
    s_arc[i] = s_arc[i-1] + sqrt(dx*dx + dy*dy);
  }
  float dx_close = shape[0][0] - shape[N_POINTS-1][0];
  float dy_close = shape[0][1] - shape[N_POINTS-1][1];
  perimeter = s_arc[N_POINTS-1] + sqrt(dx_close*dx_close + dy_close*dy_close);

  int n_cycles = round(perimeter / LAMBDA_TEX);
  if (n_cycles < 1) n_cycles = 1;
  lambda_actual = perimeter / n_cycles;
  println("Perimeter: " + perimeter + " m, " + n_cycles + " texture cycles, " +
          "lambda = " + lambda_actual + " m");
}


// =============================================================
// VISUAL RENDERING
// =============================================================
float meterToPixelX(float xm) { return ORIGIN_X + xm * PIXELS_PER_METER; }
float meterToPixelY(float ym) { return ORIGIN_Y - ym * PIXELS_PER_METER; }

void drawShape() {
  // Fill the inside with a faint color to indicate "wall force region"
  // (d > 0; linear spring pushing user outward).
  fill(240, 230, 220, 200);
  stroke(40);
  strokeWeight(2);
  beginShape();
  for (int i = 0; i < N_POINTS; i++) {
    vertex(meterToPixelX(shape[i][0]), meterToPixelY(shape[i][1]));
  }
  endShape(CLOSE);
}

// Helper: draw the outline offset outward by `offset` meters, with thick
// stroke `bandWidth` meters. Net effect is a band whose inner edge sits
// at distance `offset - bandWidth/2` from the outline, and outer edge at
// `offset + bandWidth/2`.  For a clean "entirely outside" band, set
// offset = bandWidth/2.
//
// Uses vertex-normal offsetting; can produce small artifacts at sharp
// concavities, but with modest offset values these are barely noticeable
// compared to the spiky polygon-offset approach we had before.
void drawOutlineBand(float offset, float bandWidth, int r, int g, int b, int alpha) {
  noFill();
  stroke(r, g, b, alpha);
  strokeWeight(bandWidth * PIXELS_PER_METER);
  beginShape();
  for (int i = 0; i < N_POINTS; i++) {
    int prev = (i - 1 + N_POINTS) % N_POINTS;
    float tx1 = shape[i][0] - shape[prev][0];
    float ty1 = shape[i][1] - shape[prev][1];
    float L1 = sqrt(tx1*tx1 + ty1*ty1);
    int next = (i + 1) % N_POINTS;
    float tx2 = shape[next][0] - shape[i][0];
    float ty2 = shape[next][1] - shape[i][1];
    float L2 = sqrt(tx2*tx2 + ty2*ty2);
    // Outward normal at vertex = avg of adjacent edge outward normals
    // (for CCW polygon: rotate tangent -90 deg -> (ty, -tx))
    float nx =  ((ty1/L1) + (ty2/L2)) / 2.0f;
    float ny = -((tx1/L1) + (tx2/L2)) / 2.0f;
    float L = sqrt(nx*nx + ny*ny);
    if (L < 1e-9f) continue;
    nx /= L; ny /= L;
    float x = shape[i][0] + nx * offset;
    float y = shape[i][1] + ny * offset;
    vertex(meterToPixelX(x), meterToPixelY(y));
  }
  endShape(CLOSE);
}

void drawDeadZone() {
  // Band entirely outside the outline, from d=0 to d=P_T (3 mm wide).
  float w = abs(P_T);            // 3 mm
  drawOutlineBand(w * 0.5f, w, 180, 220, 255, 180);
}

void drawGuidanceRegion() {
  // Guidance band: from d=P_T outward to the saturation distance.
  // Saturation is at d = P_T - ln(F_GUIDE_MAX/A_GUIDE)/C_GUIDE
  // = -0.003 - ln(2/0.5)/200 = -0.003 - 0.00693 = -0.00993 m.
  // So the guidance region is from d = -0.003 to d = -0.010, width ~7 mm.
  float w = 0.007f;
  float midOffset = abs(P_T) + w * 0.5f;  // band center is 6.5 mm outside outline
  drawOutlineBand(midOffset, w, 255, 200, 200, 80);
}

void drawPenTip(float xh, float yh) {
  noStroke();
  fill(255, 100, 150);
  ellipse(meterToPixelX(xh), meterToPixelY(yh), 12, 12);
}

void drawForceArrow(float xh, float yh, float Fx, float Fy) {
  float Fmag = sqrt(Fx*Fx + Fy*Fy);
  if (Fmag < 1e-4f) return;
  float SCALE = 50.0f;
  float x1 = meterToPixelX(xh);
  float y1 = meterToPixelY(yh);
  float x2 = x1 + Fx * SCALE;
  float y2 = y1 - Fy * SCALE;
  stroke(40, 160, 80);
  strokeWeight(3);
  line(x1, y1, x2, y2);
  float angle = atan2(y2 - y1, x2 - x1);
  pushMatrix();
  translate(x2, y2);
  rotate(angle);
  triangle(0, 0, -10, -5, -10, 5);
  popMatrix();
}

void drawHUD(float xh, float yh, float Fx, float Fy, float signedDepth) {
  noStroke();
  fill(255, 255, 255, 220);
  rect(10, 10, 280, 180);
  fill(20);
  textSize(13);
  text("SHAPE: " + shapeName, 20, 30);
  text("MODE: " + (STANDALONE_MODE ? "STANDALONE" : "HARDWARE"), 20, 50);
  text("RENDER: " + (texturedMode ? "TEXTURED" : "CONTROL"), 20, 70);
  text(String.format("Pen tip: (%.4f, %.4f) m", xh, yh), 20, 95);
  text(String.format("Signed depth: %.4f m", signedDepth), 20, 115);
  text(String.format("Force: (%.3f, %.3f) N", Fx, Fy), 20, 135);
  text(String.format("|F|: %.3f N", sqrt(Fx*Fx + Fy*Fy)), 20, 155);

  fill(120);
  textSize(11);
  text("[B/H/P] shape  [T] texture  [M] mode  [R] reset", 20, height - 15);
}


// =============================================================
// SERIAL
// =============================================================
void setupSerial() {
  if (STANDALONE_MODE) return;
  String[] ports = Serial.list();
  println("Available serial ports:");
  for (int i = 0; i < ports.length; i++) {
    println("  [" + i + "] " + ports[i]);
  }
  if (ports.length == 0) {
    println("No serial ports found; staying in STANDALONE mode.");
    STANDALONE_MODE = true;
    return;
  }
  String portName = SERIAL_PORT_NAME.isEmpty() ? ports[0] : SERIAL_PORT_NAME;
  println("Connecting to: " + portName);
  arduinoPort = new Serial(this, portName, 115200);
  arduinoPort.bufferUntil('\n');
}

void sendMouseToArduino(float xh, float yh) {
  if (arduinoPort == null) return;
  arduinoPort.write(String.format("%.4f,%.4f\n", xh, yh));
}


// =============================================================
// INPUT
// =============================================================
void keyPressed() {
  if (key == 'b' || key == 'B') {
    setShape(0);
  } else if (key == 'h' || key == 'H') {
    setShape(1);
  } else if (key == 'p' || key == 'P') {
    setShape(2);
  } else if (key == 't' || key == 'T') {
    texturedMode = !texturedMode;
    println("texturedMode = " + texturedMode);
    if (arduinoPort != null) {
      arduinoPort.write(texturedMode ? 'T' : 'C');
    }
  } else if (key == 'm' || key == 'M') {
    STANDALONE_MODE = !STANDALONE_MODE;
    println("STANDALONE_MODE = " + STANDALONE_MODE);
    if (!STANDALONE_MODE && arduinoPort == null) setupSerial();
  } else if (key == 'r' || key == 'R') {
    xh_prev = 0; yh_prev = 0;
    vx_filt = 0; vy_filt = 0;
  }
}
