// ============================================================
// ME327 Team 10 - Force Model Tester (Processing)
// ============================================================
// Multi-shape version. Three shapes (bunny, hammer, pear) derived from
// the same Python-generated CSVs that feed the Arduino code.
//
// Two modes:
//   STANDALONE  : compute the force model in Processing itself
//                 (no Arduino needed -- fastest way to validate the math)
//   HARDWARE    : stream mouse position to an Arduino over serial,
//                 receive force back, render it
//
// Visual:
//   - Black outline = active shape
//   - Light blue band = dead zone (P_T < d < 0, F = 0)
//   - Light red band = guidance region (d < P_T, exponential pull)
//   - Pink dot = mouse / pen-tip position
//   - Green arrow = force vector on the user
//   - Top-left HUD: shape, mode, depth, force
//
// Controls:
//   B / H / P keys : switch to Bunny / Hammer / Pear
//   T key          : toggle MODE_CONTROL <-> MODE_TEXTURED
//   M key          : toggle STANDALONE <-> HARDWARE
//   R key          : reset velocity state
// ============================================================

import processing.serial.*;

// ---------- MODE SELECTION ----------
boolean STANDALONE_MODE = true;
String SERIAL_PORT_NAME = "";       // auto-detect first port if blank

// ---------- RENDERING CONDITION ----------
boolean texturedMode = true;


// ---------- PHYSICAL <-> SCREEN MAPPING ----------
float PIXELS_PER_METER = 4000.0f;
float ORIGIN_X, ORIGIN_Y;


// ---------- FORCE MODEL PARAMETERS (must match .ino) ----------
float K_WALL       = 2000.0f;
float B_WALL       = 15.0f;
float P_T          = -0.003f;
float A_GUIDE      = 0.5f;
float C_GUIDE      = 200.0f;
float F_GUIDE_MAX  = 2.0f;
float A_TEX        = 0.30f;
float LAMBDA_TEX   = 0.0020f;


// ---------- SHAPE DATA (must match .ino) ----------
// Three shapes, each 200 points, CCW, normalized to fit ~7 cm bounding box.
// Auto-generated by preprocess_shapes.py from the team's SVG-derived CSVs.

float[][] shape_bunny = {
  {  0.00328f,  0.03500f},
  {  0.00198f,  0.03445f},
  {  0.00007f,  0.03328f},
  { -0.00150f,  0.03201f},
  { -0.00281f,  0.03115f},
  { -0.00705f,  0.02830f},
  { -0.00908f,  0.02652f},
  { -0.01059f,  0.02515f},
  { -0.01081f,  0.02493f},
  { -0.01092f,  0.02487f},
  { -0.01101f,  0.02487f},
  { -0.01108f,  0.02487f},
  { -0.01114f,  0.02487f},
  { -0.01118f,  0.02489f},
  { -0.01122f,  0.02492f},
  { -0.01125f,  0.02496f},
  { -0.01129f,  0.02500f},
  { -0.01129f,  0.02504f},
  { -0.01123f,  0.02511f},
  { -0.01117f,  0.02531f},
  { -0.01087f,  0.02665f},
  { -0.01087f,  0.02781f},
  { -0.01117f,  0.02907f},
  { -0.01147f,  0.02955f},
  { -0.01210f,  0.03042f},
  { -0.01247f,  0.03064f},
  { -0.01395f,  0.03108f},
  { -0.01449f,  0.03113f},
  { -0.01558f,  0.03088f},
  { -0.01671f,  0.03036f},
  { -0.01714f,  0.02992f},
  { -0.01752f,  0.02924f},
  { -0.01847f,  0.02674f},
  { -0.01906f,  0.02462f},
  { -0.01966f,  0.02211f},
  { -0.01993f,  0.02162f},
  { -0.02006f,  0.02134f},
  { -0.02022f,  0.02119f},
  { -0.02046f,  0.02115f},
  { -0.02206f,  0.02115f},
  { -0.02402f,  0.02085f},
  { -0.02683f,  0.01996f},
  { -0.02883f,  0.01906f},
  { -0.02986f,  0.01810f},
  { -0.03038f,  0.01725f},
  { -0.03068f,  0.01641f},
  { -0.03083f,  0.01477f},
  { -0.03159f,  0.01251f},
  { -0.03187f,  0.01112f},
  { -0.03217f,  0.00946f},
  { -0.03232f,  0.00799f},
  { -0.03247f,  0.00617f},
  { -0.03306f,  0.00375f},
  { -0.03321f,  0.00249f},
  { -0.03306f,  0.00159f},
  { -0.03260f,  0.00043f},
  { -0.03151f, -0.00111f},
  { -0.03034f, -0.00198f},
  { -0.02858f, -0.00270f},
  { -0.02674f, -0.00313f},
  { -0.02614f, -0.00335f},
  { -0.02593f, -0.00343f},
  { -0.02580f, -0.00354f},
  { -0.02577f, -0.00372f},
  { -0.02577f, -0.00418f},
  { -0.02562f, -0.00680f},
  { -0.02497f, -0.00869f},
  { -0.02430f, -0.00981f},
  { -0.02383f, -0.01151f},
  { -0.02313f, -0.01277f},
  { -0.02179f, -0.01395f},
  { -0.02012f, -0.01576f},
  { -0.01841f, -0.01689f},
  { -0.01641f, -0.01784f},
  { -0.01470f, -0.01836f},
  { -0.01451f, -0.01847f},
  { -0.01439f, -0.01852f},
  { -0.01432f, -0.01860f},
  { -0.01430f, -0.01869f},
  { -0.01430f, -0.01879f},
  { -0.01431f, -0.01892f},
  { -0.01446f, -0.01908f},
  { -0.01503f, -0.02009f},
  { -0.01549f, -0.02075f},
  { -0.01549f, -0.02125f},
  { -0.01548f, -0.02189f},
  { -0.01519f, -0.02237f},
  { -0.01460f, -0.02308f},
  { -0.01372f, -0.02381f},
  { -0.01353f, -0.02401f},
  { -0.01343f, -0.02411f},
  { -0.01340f, -0.02421f},
  { -0.01344f, -0.02431f},
  { -0.01355f, -0.02442f},
  { -0.01390f, -0.02477f},
  { -0.01474f, -0.02563f},
  { -0.01559f, -0.02765f},
  { -0.01579f, -0.02894f},
  { -0.01571f, -0.02971f},
  { -0.01522f, -0.03080f},
  { -0.01475f, -0.03142f},
  { -0.01380f, -0.03207f},
  { -0.01329f, -0.03232f},
  { -0.01214f, -0.03247f},
  { -0.01122f, -0.03232f},
  { -0.00899f, -0.03207f},
  { -0.00771f, -0.03172f},
  { -0.00628f, -0.03142f},
  { -0.00553f, -0.03113f},
  { -0.00527f, -0.03113f},
  { -0.00502f, -0.03132f},
  { -0.00413f, -0.03206f},
  { -0.00174f, -0.03415f},
  { -0.00040f, -0.03470f},
  {  0.00098f, -0.03500f},
  {  0.00178f, -0.03485f},
  {  0.00355f, -0.03443f},
  {  0.00617f, -0.03375f},
  {  0.00746f, -0.03351f},
  {  0.00828f, -0.03321f},
  {  0.01215f, -0.03232f},
  {  0.01415f, -0.03202f},
  {  0.01695f, -0.03143f},
  {  0.01793f, -0.03098f},
  {  0.01925f, -0.02990f},
  {  0.01968f, -0.02948f},
  {  0.02098f, -0.02772f},
  {  0.02209f, -0.02602f},
  {  0.02277f, -0.02519f},
  {  0.02317f, -0.02502f},
  {  0.02375f, -0.02487f},
  {  0.02573f, -0.02457f},
  {  0.02693f, -0.02427f},
  {  0.02857f, -0.02326f},
  {  0.02999f, -0.02199f},
  {  0.03133f, -0.02095f},
  {  0.03216f, -0.01967f},
  {  0.03291f, -0.01799f},
  {  0.03321f, -0.01632f},
  {  0.03306f, -0.01461f},
  {  0.03251f, -0.01300f},
  {  0.03185f, -0.01219f},
  {  0.03077f, -0.01141f},
  {  0.02972f, -0.01102f},
  {  0.02953f, -0.01091f},
  {  0.02941f, -0.01079f},
  {  0.02934f, -0.01062f},
  {  0.02934f, -0.01020f},
  {  0.02919f, -0.00838f},
  {  0.02934f, -0.00771f},
  {  0.02934f, -0.00615f},
  {  0.02890f, -0.00443f},
  {  0.02852f, -0.00275f},
  {  0.02800f, -0.00119f},
  {  0.02607f,  0.00253f},
  {  0.02398f,  0.00502f},
  {  0.02308f,  0.00594f},
  {  0.02130f,  0.00744f},
  {  0.01875f,  0.00893f},
  {  0.01602f,  0.01013f},
  {  0.01401f,  0.01057f},
  {  0.01252f,  0.01058f},
  {  0.01129f,  0.01072f},
  {  0.00982f,  0.01056f},
  {  0.00770f,  0.01013f},
  {  0.00629f,  0.00987f},
  {  0.00442f,  0.00948f},
  {  0.00154f,  0.00869f},
  { -0.00014f,  0.00834f},
  { -0.00090f,  0.00834f},
  { -0.00293f,  0.00904f},
  { -0.00535f,  0.00981f},
  { -0.00659f,  0.00983f},
  { -0.00739f,  0.01007f},
  { -0.00770f,  0.01023f},
  { -0.00845f,  0.01113f},
  { -0.00926f,  0.01283f},
  { -0.00968f,  0.01425f},
  { -0.00968f,  0.01525f},
  { -0.00957f,  0.01560f},
  { -0.00925f,  0.01607f},
  { -0.00883f,  0.01638f},
  { -0.00692f,  0.01765f},
  { -0.00462f,  0.01905f},
  { -0.00221f,  0.02040f},
  { -0.00088f,  0.02102f},
  {  0.00012f,  0.02141f},
  {  0.00176f,  0.02220f},
  {  0.00299f,  0.02281f},
  {  0.00432f,  0.02353f},
  {  0.00556f,  0.02478f},
  {  0.00626f,  0.02581f},
  {  0.00670f,  0.02706f},
  {  0.00670f,  0.02909f},
  {  0.00626f,  0.03102f},
  {  0.00570f,  0.03272f},
  {  0.00510f,  0.03347f},
  {  0.00431f,  0.03455f},
  {  0.00397f,  0.03476f},
  {  0.00328f,  0.03500f}
};

float[][] shape_hammer = {
  {  0.01861f, -0.01738f},
  {  0.01862f, -0.01740f},
  {  0.01863f, -0.01742f},
  {  0.01864f, -0.01745f},
  {  0.01867f, -0.01748f},
  {  0.01872f, -0.01751f},
  {  0.01886f, -0.01753f},
  {  0.02000f, -0.01752f},
  {  0.02049f, -0.01751f},
  {  0.02071f, -0.01746f},
  {  0.02116f, -0.01727f},
  {  0.02369f, -0.01616f},
  {  0.02512f, -0.01528f},
  {  0.02673f, -0.01401f},
  {  0.02831f, -0.01247f},
  {  0.02961f, -0.01089f},
  {  0.03057f, -0.00940f},
  {  0.03150f, -0.00754f},
  {  0.03217f, -0.00571f},
  {  0.03275f, -0.00326f},
  {  0.03315f, -0.00047f},
  {  0.03318f,  0.00067f},
  {  0.03312f,  0.00140f},
  {  0.03299f,  0.00199f},
  {  0.03278f,  0.00258f},
  {  0.03240f,  0.00334f},
  {  0.03171f,  0.00460f},
  {  0.03157f,  0.00493f},
  {  0.03152f,  0.00513f},
  {  0.03149f,  0.00551f},
  {  0.03150f,  0.00668f},
  {  0.03154f,  0.00701f},
  {  0.03162f,  0.00728f},
  {  0.03179f,  0.00768f},
  {  0.03194f,  0.00797f},
  {  0.03211f,  0.00820f},
  {  0.03234f,  0.00844f},
  {  0.03276f,  0.00878f},
  {  0.03384f,  0.00949f},
  {  0.03401f,  0.00964f},
  {  0.03413f,  0.00976f},
  {  0.03422f,  0.00990f},
  {  0.03431f,  0.01007f},
  {  0.03440f,  0.01031f},
  {  0.03452f,  0.01081f},
  {  0.03496f,  0.01395f},
  {  0.03500f,  0.01436f},
  {  0.03499f,  0.01450f},
  {  0.03496f,  0.01464f},
  {  0.03490f,  0.01483f},
  {  0.03478f,  0.01508f},
  {  0.03457f,  0.01541f},
  {  0.03426f,  0.01578f},
  {  0.03392f,  0.01610f},
  {  0.03364f,  0.01632f},
  {  0.03336f,  0.01648f},
  {  0.03304f,  0.01662f},
  {  0.03256f,  0.01675f},
  {  0.03136f,  0.01692f},
  {  0.02660f,  0.01751f},
  {  0.02614f,  0.01753f},
  {  0.02599f,  0.01752f},
  {  0.02589f,  0.01749f},
  {  0.02581f,  0.01746f},
  {  0.02573f,  0.01742f},
  {  0.02564f,  0.01736f},
  {  0.02555f,  0.01729f},
  {  0.02548f,  0.01722f},
  {  0.02542f,  0.01713f},
  {  0.02536f,  0.01701f},
  {  0.02529f,  0.01682f},
  {  0.02518f,  0.01626f},
  {  0.02468f,  0.01209f},
  {  0.02467f,  0.01161f},
  {  0.02470f,  0.01138f},
  {  0.02474f,  0.01122f},
  {  0.02479f,  0.01108f},
  {  0.02487f,  0.01093f},
  {  0.02503f,  0.01072f},
  {  0.02581f,  0.00986f},
  {  0.02615f,  0.00940f},
  {  0.02635f,  0.00904f},
  {  0.02649f,  0.00872f},
  {  0.02659f,  0.00837f},
  {  0.02665f,  0.00793f},
  {  0.02667f,  0.00749f},
  {  0.02663f,  0.00708f},
  {  0.02654f,  0.00669f},
  {  0.02641f,  0.00630f},
  {  0.02623f,  0.00592f},
  {  0.02599f,  0.00555f},
  {  0.02568f,  0.00518f},
  {  0.02538f,  0.00489f},
  {  0.02513f,  0.00470f},
  {  0.02489f,  0.00457f},
  {  0.02465f,  0.00447f},
  {  0.02435f,  0.00439f},
  {  0.02396f,  0.00433f},
  {  0.02330f,  0.00431f},
  {  0.01924f,  0.00478f},
  {  0.00341f,  0.00674f},
  { -0.00959f,  0.00836f},
  { -0.01064f,  0.00850f},
  { -0.01075f,  0.00852f},
  { -0.01082f,  0.00852f},
  { -0.01088f,  0.00853f},
  { -0.01093f,  0.00854f},
  { -0.01097f,  0.00857f},
  { -0.01098f,  0.00862f},
  { -0.01099f,  0.00868f},
  { -0.01100f,  0.00875f},
  { -0.01107f,  0.00897f},
  { -0.01114f,  0.00911f},
  { -0.01122f,  0.00921f},
  { -0.01131f,  0.00930f},
  { -0.01144f,  0.00940f},
  { -0.01161f,  0.00951f},
  { -0.01184f,  0.00961f},
  { -0.01219f,  0.00972f},
  { -0.01280f,  0.00982f},
  { -0.02603f,  0.01149f},
  { -0.03026f,  0.01199f},
  { -0.03044f,  0.01202f},
  { -0.03097f,  0.01225f},
  { -0.03139f,  0.01245f},
  { -0.03157f,  0.01249f},
  { -0.03176f,  0.01251f},
  { -0.03198f,  0.01251f},
  { -0.03225f,  0.01247f},
  { -0.03254f,  0.01239f},
  { -0.03287f,  0.01227f},
  { -0.03319f,  0.01210f},
  { -0.03347f,  0.01190f},
  { -0.03369f,  0.01170f},
  { -0.03387f,  0.01149f},
  { -0.03398f,  0.01133f},
  { -0.03405f,  0.01119f},
  { -0.03415f,  0.01088f},
  { -0.03455f,  0.00884f},
  { -0.03498f,  0.00527f},
  { -0.03500f,  0.00464f},
  { -0.03498f,  0.00448f},
  { -0.03492f,  0.00425f},
  { -0.03481f,  0.00396f},
  { -0.03465f,  0.00368f},
  { -0.03449f,  0.00345f},
  { -0.03433f,  0.00327f},
  { -0.03415f,  0.00312f},
  { -0.03396f,  0.00299f},
  { -0.03376f,  0.00290f},
  { -0.03355f,  0.00282f},
  { -0.03332f,  0.00277f},
  { -0.03299f,  0.00275f},
  { -0.03152f,  0.00275f},
  { -0.02771f,  0.00232f},
  { -0.01427f,  0.00067f},
  { -0.01329f,  0.00060f},
  { -0.01306f,  0.00061f},
  { -0.01282f,  0.00065f},
  { -0.01263f,  0.00071f},
  { -0.01247f,  0.00078f},
  { -0.01234f,  0.00087f},
  { -0.01220f,  0.00099f},
  { -0.01196f,  0.00128f},
  { -0.01189f,  0.00139f},
  { -0.01184f,  0.00146f},
  { -0.01181f,  0.00151f},
  { -0.01176f,  0.00153f},
  { -0.01170f,  0.00152f},
  { -0.01164f,  0.00151f},
  { -0.01155f,  0.00150f},
  { -0.01141f,  0.00148f},
  { -0.00468f,  0.00062f},
  {  0.00954f, -0.00116f},
  {  0.02021f, -0.00251f},
  {  0.02112f, -0.00271f},
  {  0.02165f, -0.00289f},
  {  0.02207f, -0.00310f},
  {  0.02245f, -0.00335f},
  {  0.02288f, -0.00371f},
  {  0.02328f, -0.00413f},
  {  0.02358f, -0.00455f},
  {  0.02383f, -0.00499f},
  {  0.02402f, -0.00545f},
  {  0.02416f, -0.00594f},
  {  0.02423f, -0.00644f},
  {  0.02425f, -0.00698f},
  {  0.02420f, -0.00746f},
  {  0.02407f, -0.00809f},
  {  0.02373f, -0.00906f},
  {  0.02302f, -0.01054f},
  {  0.02175f, -0.01258f},
  {  0.01997f, -0.01484f},
  {  0.01887f, -0.01610f},
  {  0.01873f, -0.01631f},
  {  0.01866f, -0.01642f},
  {  0.01862f, -0.01657f},
  {  0.01858f, -0.01676f},
  {  0.01857f, -0.01703f},
  {  0.01861f, -0.01738f}
};

float[][] shape_pear = {
  { -0.00260f,  0.03430f},
  { -0.00341f,  0.03469f},
  { -0.00377f,  0.03482f},
  { -0.00411f,  0.03490f},
  { -0.00453f,  0.03496f},
  { -0.00528f,  0.03500f},
  { -0.01129f,  0.03475f},
  { -0.01401f,  0.03468f},
  { -0.01441f,  0.03464f},
  { -0.01462f,  0.03460f},
  { -0.01476f,  0.03455f},
  { -0.01485f,  0.03451f},
  { -0.01493f,  0.03448f},
  { -0.01499f,  0.03444f},
  { -0.01503f,  0.03440f},
  { -0.01507f,  0.03436f},
  { -0.01511f,  0.03432f},
  { -0.01514f,  0.03428f},
  { -0.01516f,  0.03423f},
  { -0.01519f,  0.03418f},
  { -0.01521f,  0.03412f},
  { -0.01522f,  0.03405f},
  { -0.01523f,  0.03397f},
  { -0.01523f,  0.03387f},
  { -0.01522f,  0.03373f},
  { -0.01519f,  0.03353f},
  { -0.01510f,  0.03319f},
  { -0.01481f,  0.03243f},
  { -0.01305f,  0.02866f},
  { -0.01240f,  0.02751f},
  { -0.01193f,  0.02685f},
  { -0.01127f,  0.02609f},
  { -0.01059f,  0.02542f},
  { -0.00997f,  0.02492f},
  { -0.00935f,  0.02450f},
  { -0.00871f,  0.02416f},
  { -0.00807f,  0.02389f},
  { -0.00744f,  0.02369f},
  { -0.00680f,  0.02355f},
  { -0.00617f,  0.02348f},
  { -0.00555f,  0.02346f},
  { -0.00494f,  0.02350f},
  { -0.00435f,  0.02359f},
  { -0.00376f,  0.02374f},
  { -0.00319f,  0.02395f},
  { -0.00263f,  0.02421f},
  { -0.00209f,  0.02453f},
  { -0.00111f,  0.02522f},
  { -0.00076f,  0.02542f},
  { -0.00056f,  0.02552f},
  { -0.00042f,  0.02557f},
  { -0.00032f,  0.02559f},
  { -0.00023f,  0.02561f},
  { -0.00016f,  0.02561f},
  { -0.00010f,  0.02561f},
  { -0.00005f,  0.02560f},
  {  0.00000f,  0.02559f},
  {  0.00005f,  0.02557f},
  {  0.00010f,  0.02555f},
  {  0.00014f,  0.02552f},
  {  0.00018f,  0.02549f},
  {  0.00023f,  0.02545f},
  {  0.00028f,  0.02540f},
  {  0.00033f,  0.02534f},
  {  0.00039f,  0.02525f},
  {  0.00045f,  0.02512f},
  {  0.00053f,  0.02492f},
  {  0.00064f,  0.02455f},
  {  0.00079f,  0.02375f},
  {  0.00085f,  0.02332f},
  {  0.00085f,  0.02321f},
  {  0.00085f,  0.02315f},
  {  0.00084f,  0.02311f},
  {  0.00082f,  0.02307f},
  {  0.00081f,  0.02304f},
  {  0.00079f,  0.02301f},
  {  0.00077f,  0.02298f},
  {  0.00075f,  0.02295f},
  {  0.00072f,  0.02292f},
  {  0.00068f,  0.02289f},
  {  0.00062f,  0.02285f},
  {  0.00054f,  0.02281f},
  {  0.00042f,  0.02277f},
  {  0.00019f,  0.02270f},
  { -0.00070f,  0.02257f},
  { -0.00157f,  0.02241f},
  { -0.00224f,  0.02222f},
  { -0.00290f,  0.02195f},
  { -0.00358f,  0.02160f},
  { -0.00429f,  0.02116f},
  { -0.00504f,  0.02058f},
  { -0.00584f,  0.01983f},
  { -0.00672f,  0.01885f},
  { -0.00769f,  0.01754f},
  { -0.00879f,  0.01575f},
  { -0.01004f,  0.01322f},
  { -0.01149f,  0.00954f},
  { -0.01266f,  0.00631f},
  { -0.01349f,  0.00460f},
  { -0.01505f,  0.00202f},
  { -0.01927f, -0.00416f},
  { -0.02083f, -0.00682f},
  { -0.02176f, -0.00879f},
  { -0.02237f, -0.01046f},
  { -0.02278f, -0.01201f},
  { -0.02304f, -0.01356f},
  { -0.02317f, -0.01525f},
  { -0.02315f, -0.01707f},
  { -0.02299f, -0.01870f},
  { -0.02267f, -0.02030f},
  { -0.02222f, -0.02187f},
  { -0.02162f, -0.02340f},
  { -0.02088f, -0.02488f},
  { -0.01999f, -0.02631f},
  { -0.01897f, -0.02767f},
  { -0.01781f, -0.02895f},
  { -0.01653f, -0.03014f},
  { -0.01511f, -0.03122f},
  { -0.01359f, -0.03219f},
  { -0.01195f, -0.03304f},
  { -0.01021f, -0.03374f},
  { -0.00846f, -0.03428f},
  { -0.00747f, -0.03448f},
  { -0.00439f, -0.03480f},
  {  0.00239f, -0.03500f},
  {  0.00669f, -0.03483f},
  {  0.00801f, -0.03466f},
  {  0.00902f, -0.03441f},
  {  0.01060f, -0.03389f},
  {  0.01221f, -0.03318f},
  {  0.01381f, -0.03231f},
  {  0.01536f, -0.03126f},
  {  0.01682f, -0.03008f},
  {  0.01816f, -0.02878f},
  {  0.01933f, -0.02742f},
  {  0.02032f, -0.02602f},
  {  0.02114f, -0.02463f},
  {  0.02178f, -0.02327f},
  {  0.02226f, -0.02195f},
  {  0.02277f, -0.02000f},
  {  0.02306f, -0.01830f},
  {  0.02317f, -0.01680f},
  {  0.02315f, -0.01531f},
  {  0.02298f, -0.01371f},
  {  0.02260f, -0.01177f},
  {  0.02181f, -0.00908f},
  {  0.01996f, -0.00436f},
  {  0.01721f,  0.00200f},
  {  0.01520f,  0.00772f},
  {  0.01368f,  0.01217f},
  {  0.01251f,  0.01483f},
  {  0.01155f,  0.01657f},
  {  0.01074f,  0.01776f},
  {  0.01004f,  0.01861f},
  {  0.00943f,  0.01923f},
  {  0.00888f,  0.01969f},
  {  0.00838f,  0.02004f},
  {  0.00791f,  0.02030f},
  {  0.00745f,  0.02050f},
  {  0.00701f,  0.02065f},
  {  0.00634f,  0.02079f},
  {  0.00587f,  0.02090f},
  {  0.00564f,  0.02099f},
  {  0.00549f,  0.02105f},
  {  0.00538f,  0.02112f},
  {  0.00530f,  0.02118f},
  {  0.00523f,  0.02124f},
  {  0.00517f,  0.02130f},
  {  0.00512f,  0.02136f},
  {  0.00508f,  0.02143f},
  {  0.00504f,  0.02152f},
  {  0.00498f,  0.02167f},
  {  0.00487f,  0.02226f},
  {  0.00393f,  0.02751f},
  {  0.00380f,  0.02806f},
  {  0.00365f,  0.02849f},
  {  0.00347f,  0.02888f},
  {  0.00328f,  0.02921f},
  {  0.00309f,  0.02949f},
  {  0.00290f,  0.02971f},
  {  0.00272f,  0.02989f},
  {  0.00254f,  0.03002f},
  {  0.00238f,  0.03013f},
  {  0.00223f,  0.03021f},
  {  0.00208f,  0.03027f},
  {  0.00193f,  0.03032f},
  {  0.00161f,  0.03036f},
  {  0.00146f,  0.03039f},
  {  0.00136f,  0.03042f},
  {  0.00126f,  0.03047f},
  {  0.00115f,  0.03054f},
  {  0.00100f,  0.03064f},
  {  0.00081f,  0.03080f},
  {  0.00056f,  0.03107f},
  {  0.00018f,  0.03156f},
  { -0.00047f,  0.03249f},
  { -0.00094f,  0.03302f},
  { -0.00145f,  0.03350f},
  { -0.00197f,  0.03390f},
  { -0.00260f,  0.03430f}
};

// Active shape (pointer + length).
float[][] shape;
int N_POINTS;
String shapeName;

void setShape(int id) {
  switch (id) {
    case 0: shape = shape_bunny;  shapeName = "BUNNY";  break;
    case 1: shape = shape_hammer; shapeName = "HAMMER"; break;
    case 2: shape = shape_pear;   shapeName = "PEAR";   break;
  }
  N_POINTS = shape.length;
  precomputeArcLength();
  println("Active shape: " + shapeName + " (" + N_POINTS + " pts)");

  // Tell Arduino too, if connected.
  if (arduinoPort != null) {
    if (id == 0)      arduinoPort.write('B');
    else if (id == 1) arduinoPort.write('H');
    else if (id == 2) arduinoPort.write('P');
  }
}


// Precomputed arc-length table (sized for max possible):
float[] s_arc;
float perimeter;
float lambda_actual;


// ---------- VELOCITY TRACKING ----------
float xh_prev = 0, yh_prev = 0;
float vx_filt = 0, vy_filt = 0;
float DT_LOOP = 0.001f;


// ---------- SERIAL ----------
Serial arduinoPort = null;
float arduinoFx = 0, arduinoFy = 0;


// =============================================================
// SETUP
// =============================================================
void setup() {
  size(900, 900);
  ORIGIN_X = width / 2.0f;
  ORIGIN_Y = height / 2.0f;

  setShape(0);   // start with bunny
  setupSerial();
}


// =============================================================
// DRAW LOOP
// =============================================================
void draw() {
  background(245);

  float xh = (mouseX - ORIGIN_X) / PIXELS_PER_METER;
  float yh = -(mouseY - ORIGIN_Y) / PIXELS_PER_METER;

  float vx_raw = (xh - xh_prev) / DT_LOOP;
  float vy_raw = (yh - yh_prev) / DT_LOOP;
  vx_filt = 0.9f * vx_raw + 0.1f * vx_filt;
  vy_filt = 0.9f * vy_raw + 0.1f * vy_filt;
  xh_prev = xh;
  yh_prev = yh;

  float[] F;
  float signedDepth;
  if (STANDALONE_MODE) {
    F = computeForceStandalone(xh, yh);
  } else {
    sendMouseToArduino(xh, yh);
    F = new float[]{arduinoFx, arduinoFy};
    computeForceStandalone(xh, yh);  // also run locally for HUD depth value
  }
  signedDepth = lastSignedDepth;

  drawGuidanceRegion();
  drawDeadZone();
  drawShape();
  drawPenTip(xh, yh);
  drawForceArrow(xh, yh, F[0], F[1]);
  drawHUD(xh, yh, F[0], F[1], signedDepth);
}


// =============================================================
// FORCE MODEL (standalone)
// =============================================================
float lastSignedDepth = 0;

float[] computeForceStandalone(float x, float y) {
  float[] result = findNearestSegment(x, y);
  float unsigned_d = result[0];
  float nx = result[1];
  float ny = result[2];
  float t_frac = result[3];
  int seg_i = (int) result[4];

  boolean inside = isInsidePolygon(x, y);
  float d = inside ? unsigned_d : -unsigned_d;
  lastSignedDepth = d;

  float v_inward = -(vx_filt * nx + vy_filt * ny);

  float Fx = 0, Fy = 0;

  if (d > 0.0f) {
    float F_wall_mag = K_WALL * d;
    if (v_inward > 0.0f) F_wall_mag += B_WALL * v_inward;
    Fx = F_wall_mag * nx;
    Fy = F_wall_mag * ny;

    if (texturedMode) {
      int next_i = (seg_i + 1) % N_POINTS;
      float seg_len = (next_i == 0) ? (perimeter - s_arc[seg_i])
                                    : (s_arc[next_i] - s_arc[seg_i]);
      float s = s_arc[seg_i] + t_frac * seg_len;
      float F_tex = A_TEX * sin(2 * PI * s / lambda_actual);
      Fx += F_tex * nx;
      Fy += F_tex * ny;
    }
  } else if (d > P_T) {
    Fx = 0; Fy = 0;
  } else {
    float F_guide = A_GUIDE * exp(-C_GUIDE * (d - P_T));
    if (F_guide > F_GUIDE_MAX) F_guide = F_GUIDE_MAX;
    Fx = -F_guide * nx;
    Fy = -F_guide * ny;
  }

  return new float[]{Fx, Fy};
}


float[] findNearestSegment(float x, float y) {
  int best_i = 0;
  float best_dist = 1e9f;
  float best_nx = 0, best_ny = 0, best_t = 0;

  for (int i = 0; i < N_POINTS; i++) {
    int j = (i + 1) % N_POINTS;
    float ax = shape[i][0], ay = shape[i][1];
    float bx = shape[j][0], by = shape[j][1];
    float tx = bx - ax;
    float ty = by - ay;
    float seg_len2 = tx*tx + ty*ty;

    float t = ((x - ax)*tx + (y - ay)*ty) / seg_len2;
    if (t < 0) t = 0;
    if (t > 1) t = 1;

    float px = ax + t*tx;
    float py = ay + t*ty;
    float ddx = x - px;
    float ddy = y - py;
    float d = sqrt(ddx*ddx + ddy*ddy);

    if (d < best_dist) {
      best_dist = d;
      best_i = i;
      best_t = t;
      float seg_len = sqrt(seg_len2);
      // Outward normal for a CCW polygon in math (y-up) coords:
      // rotate tangent -90 deg, i.e. (tx, ty) -> (ty, -tx).
      best_nx =  ty / seg_len;
      best_ny = -tx / seg_len;
    }
  }
  return new float[]{best_dist, best_nx, best_ny, best_t, best_i};
}


boolean isInsidePolygon(float x, float y) {
  boolean inside = false;
  for (int i = 0, j = N_POINTS - 1; i < N_POINTS; j = i++) {
    float xi = shape[i][0], yi = shape[i][1];
    float xj = shape[j][0], yj = shape[j][1];
    boolean intersect = ((yi > y) != (yj > y)) &&
                       (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
    if (intersect) inside = !inside;
  }
  return inside;
}


void precomputeArcLength() {
  s_arc = new float[N_POINTS];
  s_arc[0] = 0;
  for (int i = 1; i < N_POINTS; i++) {
    float dx = shape[i][0] - shape[i-1][0];
    float dy = shape[i][1] - shape[i-1][1];
    s_arc[i] = s_arc[i-1] + sqrt(dx*dx + dy*dy);
  }
  float dx_close = shape[0][0] - shape[N_POINTS-1][0];
  float dy_close = shape[0][1] - shape[N_POINTS-1][1];
  perimeter = s_arc[N_POINTS-1] + sqrt(dx_close*dx_close + dy_close*dy_close);

  int n_cycles = round(perimeter / LAMBDA_TEX);
  if (n_cycles < 1) n_cycles = 1;
  lambda_actual = perimeter / n_cycles;
  println("Perimeter: " + perimeter + " m, " + n_cycles + " texture cycles, " +
          "lambda = " + lambda_actual + " m");
}


// =============================================================
// VISUAL RENDERING
// =============================================================
float meterToPixelX(float xm) { return ORIGIN_X + xm * PIXELS_PER_METER; }
float meterToPixelY(float ym) { return ORIGIN_Y - ym * PIXELS_PER_METER; }

void drawShape() {
  // Fill the inside with a faint color to indicate "wall force region"
  // (d > 0; linear spring pushing user outward).
  fill(240, 230, 220, 200);
  stroke(40);
  strokeWeight(2);
  beginShape();
  for (int i = 0; i < N_POINTS; i++) {
    vertex(meterToPixelX(shape[i][0]), meterToPixelY(shape[i][1]));
  }
  endShape(CLOSE);
}

// Helper: draw the outline offset outward by `offset` meters, with thick
// stroke `bandWidth` meters. Net effect is a band whose inner edge sits
// at distance `offset - bandWidth/2` from the outline, and outer edge at
// `offset + bandWidth/2`.  For a clean "entirely outside" band, set
// offset = bandWidth/2.
//
// Uses vertex-normal offsetting; can produce small artifacts at sharp
// concavities, but with modest offset values these are barely noticeable
// compared to the spiky polygon-offset approach we had before.
void drawOutlineBand(float offset, float bandWidth, int r, int g, int b, int alpha) {
  noFill();
  stroke(r, g, b, alpha);
  strokeWeight(bandWidth * PIXELS_PER_METER);
  beginShape();
  for (int i = 0; i < N_POINTS; i++) {
    int prev = (i - 1 + N_POINTS) % N_POINTS;
    float tx1 = shape[i][0] - shape[prev][0];
    float ty1 = shape[i][1] - shape[prev][1];
    float L1 = sqrt(tx1*tx1 + ty1*ty1);
    int next = (i + 1) % N_POINTS;
    float tx2 = shape[next][0] - shape[i][0];
    float ty2 = shape[next][1] - shape[i][1];
    float L2 = sqrt(tx2*tx2 + ty2*ty2);
    // Outward normal at vertex = avg of adjacent edge outward normals
    // (for CCW polygon: rotate tangent -90 deg -> (ty, -tx))
    float nx =  ((ty1/L1) + (ty2/L2)) / 2.0f;
    float ny = -((tx1/L1) + (tx2/L2)) / 2.0f;
    float L = sqrt(nx*nx + ny*ny);
    if (L < 1e-9f) continue;
    nx /= L; ny /= L;
    float x = shape[i][0] + nx * offset;
    float y = shape[i][1] + ny * offset;
    vertex(meterToPixelX(x), meterToPixelY(y));
  }
  endShape(CLOSE);
}

void drawDeadZone() {
  // Band entirely outside the outline, from d=0 to d=P_T (3 mm wide).
  float w = abs(P_T);            // 3 mm
  drawOutlineBand(w * 0.5f, w, 180, 220, 255, 180);
}

void drawGuidanceRegion() {
  // Guidance band: from d=P_T outward to the saturation distance.
  // Saturation is at d = P_T - ln(F_GUIDE_MAX/A_GUIDE)/C_GUIDE
  // = -0.003 - ln(2/0.5)/200 = -0.003 - 0.00693 = -0.00993 m.
  // So the guidance region is from d = -0.003 to d = -0.010, width ~7 mm.
  float w = 0.007f;
  float midOffset = abs(P_T) + w * 0.5f;  // band center is 6.5 mm outside outline
  drawOutlineBand(midOffset, w, 255, 200, 200, 80);
}

void drawPenTip(float xh, float yh) {
  noStroke();
  fill(255, 100, 150);
  ellipse(meterToPixelX(xh), meterToPixelY(yh), 12, 12);
}

void drawForceArrow(float xh, float yh, float Fx, float Fy) {
  float Fmag = sqrt(Fx*Fx + Fy*Fy);
  if (Fmag < 1e-4f) return;
  float SCALE = 50.0f;
  float x1 = meterToPixelX(xh);
  float y1 = meterToPixelY(yh);
  float x2 = x1 + Fx * SCALE;
  float y2 = y1 - Fy * SCALE;
  stroke(40, 160, 80);
  strokeWeight(3);
  line(x1, y1, x2, y2);
  float angle = atan2(y2 - y1, x2 - x1);
  pushMatrix();
  translate(x2, y2);
  rotate(angle);
  triangle(0, 0, -10, -5, -10, 5);
  popMatrix();
}

void drawHUD(float xh, float yh, float Fx, float Fy, float signedDepth) {
  noStroke();
  fill(255, 255, 255, 220);
  rect(10, 10, 280, 180);
  fill(20);
  textSize(13);
  text("SHAPE: " + shapeName, 20, 30);
  text("MODE: " + (STANDALONE_MODE ? "STANDALONE" : "HARDWARE"), 20, 50);
  text("RENDER: " + (texturedMode ? "TEXTURED" : "CONTROL"), 20, 70);
  text(String.format("Pen tip: (%.4f, %.4f) m", xh, yh), 20, 95);
  text(String.format("Signed depth: %.4f m", signedDepth), 20, 115);
  text(String.format("Force: (%.3f, %.3f) N", Fx, Fy), 20, 135);
  text(String.format("|F|: %.3f N", sqrt(Fx*Fx + Fy*Fy)), 20, 155);

  fill(120);
  textSize(11);
  text("[B/H/P] shape  [T] texture  [M] mode  [R] reset", 20, height - 15);
}


// =============================================================
// SERIAL
// =============================================================
void setupSerial() {
  if (STANDALONE_MODE) return;
  String[] ports = Serial.list();
  println("Available serial ports:");
  for (int i = 0; i < ports.length; i++) {
    println("  [" + i + "] " + ports[i]);
  }
  if (ports.length == 0) {
    println("No serial ports found; staying in STANDALONE mode.");
    STANDALONE_MODE = true;
    return;
  }
  String portName = SERIAL_PORT_NAME.isEmpty() ? ports[0] : SERIAL_PORT_NAME;
  println("Connecting to: " + portName);
  arduinoPort = new Serial(this, portName, 115200);
  arduinoPort.bufferUntil('\n');
}

void sendMouseToArduino(float xh, float yh) {
  if (arduinoPort == null) return;
  arduinoPort.write(String.format("%.4f,%.4f\n", xh, yh));
}


// =============================================================
// INPUT
// =============================================================
void keyPressed() {
  if (key == 'b' || key == 'B') {
    setShape(0);
  } else if (key == 'h' || key == 'H') {
    setShape(1);
  } else if (key == 'p' || key == 'P') {
    setShape(2);
  } else if (key == 't' || key == 'T') {
    texturedMode = !texturedMode;
    println("texturedMode = " + texturedMode);
    if (arduinoPort != null) {
      arduinoPort.write(texturedMode ? 'T' : 'C');
    }
  } else if (key == 'm' || key == 'M') {
    STANDALONE_MODE = !STANDALONE_MODE;
    println("STANDALONE_MODE = " + STANDALONE_MODE);
    if (!STANDALONE_MODE && arduinoPort == null) setupSerial();
  } else if (key == 'r' || key == 'R') {
    xh_prev = 0; yh_prev = 0;
    vx_filt = 0; vy_filt = 0;
  }
}
